(* ::Package:: *)

(************************************************************************)\012(* This file was generated automatically by the Mathematica front end.  *)\012(* It contains Initialization cells from a Notebook file, which         *)\012(* typically will have the same name as this file except ending in      *)\012(* ".nb" instead of ".m".                                               *)\012(*                                                                      *)\012(* This file is intended to be loaded into the Mathematica kernel using *)\012(* the package loading commands Get or Needs.  Doing so is equivalent   *)\012(* to using the Evaluate Initialization Cells menu command in the front *)\012(* end.                                                                 *)\012(*                                                                      *)\012(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)\012(* automatically each time the parent Notebook file is saved in the     *)\012(* Mathematica front end.  Any changes you make to this file will be    *)\012(* overwritten.                                                         *)\012(************************************************************************)\012\012

(*
Copyright (c) 2026 Peter Overmann
 
SPDX-License-Identifier: MIT
 
This file is part of the "Creating Intelligence" project. It is licensed 
under the MIT License. You may obtain a copy of the License in the LICENSE 
file in the root directory of this repository.
 
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR 
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, 
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
*)


<< "Memory.m"


(*
This package processes sparse sets and multisets through user-defined circuits.
Data flow is controlled by paths that connect various circuit components.
Associative memory functionality is isolated in specific types
of memory components.

Paths are either "digital" sets of integers i > 0, or "analog"
multisets of integers i > 0 for excitatory and i < 0 for inhibitory 
signals.

Partitioned multisets may be formed through the disjoint aggregation
of individual multisets. We refer to this mechanism as block coding.

All components must properly handle the presence of negative elements. 
The memory components systematically apply and then drop inhibitory 
elements, because the associative memory algorithms are inherently digital.
*)


(* 
Summates excitatory and inhibitory signals.
Outputs a net multiset. 
No element will exist as both positive and negative. 
*)

Multiset[u___List] := Module[{x, tally},

	x = Flatten[{u}];
	
	(* Tally positives, tally negatives, and add them together *)
	tally = Merge[{
				Counts[Select[x, # > 0 &]], 
				(* Shift to positive, but make counts negative. *)
				-Counts[-Select[x, # < 0 &]] 
				}, Total];
	
	(* Reconstruct the net multiset. *)
	Sort @ Flatten @ KeyValueMap[
		If[#2 == 0, 
			{}, (* Exact cancellation. *)
			(* Restore sign and multiplicity *)
			ConstantArray[Sign[#2] * #1, Abs[#2]] 
		] &, tally]
	]


(* Applies graded inhibition, drops negatives, squashes excitatory survivors. *)

ResolveNormal[x_List] := Module[{AE, AI, countsE, countsI},

	AE =  Select[x, # > 0 &];
	AI = -Select[x, # < 0 &]; 
	
	If[AI === {}, Return[Union[AE]]]; (* Fast path for pure boolean. *)
	
	countsE = Counts[AE];
	countsI = Counts[AI];
	
	Sort[Select[Keys[countsE], countsE[#] > Lookup[countsI, #, 0] &]]
	]


(* Applies graded inhibition, drops negatives, keeps excitatory survivors. *)

ResolveGraded[x_List] := Module[{AE, AI, countsE, countsI},

	AE =  Select[x, # > 0 &];
	AI = -Select[x, # < 0 &];
	
	If[AI === {}, Return[Sort[AE]]]; (* Fast path for pure multisets. *)
	
	countsE = Counts[AE];
	countsI = Counts[AI];
	
	Sort[Flatten @ KeyValueMap[
		ConstantArray[#1, Max[0, #2 - Lookup[countsI, #1, 0]]] &, 
		countsE ]]
	]


(* 
Transparently joins multisets. Preserves duplicates and negative signs. 
*)

MultisetBlockJoin[blocks : {__List}, dims : {__Integer}] := Module[{offsets},
	(* Calculate the starting index for each block *)
	offsets = FoldList[Plus, 0, Most[dims]];
	
	Flatten @ MapThread[
		Function[{sublist, offset},
			(* Shift absolute IDs to prevent collision, then restore the sign *)
			Sign[sublist] * (Abs[sublist] + offset)
		],
		{blocks, offsets} ]
	]


(* 
Transparently splits a joined multiset back into its original blocks. 
*)

MultisetBlockSplit[A_List, dims : {__Integer}] := Module[{limits, bounds},
	
	(* Calculate the ID boundaries for each block *)
	limits = FoldList[Plus, 0, dims];
	bounds = Partition[limits, 2, 1];
	
	Map[
		Function[{b},
			(* Select elements whose absolute ID falls in this block's range. *)
			Module[{chunk = Select[A, b[[1]] < Abs[#] <= b[[2]] &]},
				(* Remove the offset and restore the sign. *)
				Sign[chunk] * (Abs[chunk] - b[[1]])
			]
		], bounds ]
	]


(* 
Join blocks {A1,A2,...} with dimensions {n1,n2,...} into a single list. 
Applies graded inhibition and drops inhibitory elements. 
Preserves multisets. 
*)
MultisetBlockJoinNormal[blocks : {__List}, dims : {__Integer}] := 
	Module[ {join, signs, AE, AI, countsE, countsI, netExcitatory},

	(* Add offsets to each block to ensure disjoint ID spaces. *)
	join = Function[{x}, Flatten[x + FoldList[Plus, 0, Most[dims]]]];
	
	signs = Sign /@ blocks;
	
	(* Extract and offset excitatory and inhibitory elements. *)
	AE = join[ MapThread[  Pick[#1,#2, 1]&, {blocks, signs}]];
	AI = join[ MapThread[ -Pick[#1,#2,-1]&, {blocks, signs}]];

	(* Count frequencies for graded subtraction. *)
	countsE = Counts[AE];
	countsI = Counts[AI];
	
	(* Graded Subtraction: Excitatory count minus Inhibitory count, 
		floored at zero. *)
	netExcitatory = Flatten @ KeyValueMap[
		ConstantArray[#1, Max[0, #2 - Lookup[countsI, #1, 0]]] &, 
		countsE
		];
	
	(* Return the surviving excitatory multiset. Negatives are dropped. *)
	Sort[netExcitatory]
	]


(*
Applies graded subtraction, drops negatives, and squashes the survivors. 
Outputs a flat, Boolean excitatory set.
*)

ResolveBlockJoinNormal[blocks: {__List}, dims : {__Integer}] := 
	Module[{join, signs, AE, AI, countsE, countsI, survivors},

	(* Add offsets to each block to ensure disjoint ID spaces *)
	join = Function[{x}, Flatten[x + FoldList[Plus, 0, Most[dims]]]];
	signs = Sign /@ blocks;
	
	(* Extract and offset excitatory and inhibitory elements. *)
	AE = join[MapThread[  Pick[#1,#2, 1]&, {blocks, signs}]];
	AI = join[MapThread[ -Pick[#1,#2,-1]&, {blocks, signs}]];

	(* Count frequencies for graded evaluation *)
	countsE = Counts[AE];
	countsI = Counts[AI];
	
	(* Squash: An element survives only if excitation  exceeds inhibition. *)
	survivors = Select[Keys[countsE], countsE[#] > Lookup[countsI, #, 0] &];
	
	Sort[survivors]
	]


MemoryCapacity[{N_, P_}, {N_, _}] := (* Auto-associative. *)
	Round[ Log[2] * (N * (N-1) * (N-2)) / (P * (P-1) * (P-2) ) ];
	
MemoryCapacity[{NA_, PA_}, {NB_, PB_}] := (* Hetero-associative. *)
	Round[ Log[2] * (NB * NA * (NA-1)) / (PB * PA * (PA-1) ) ];


MatchingThreshold[{NA_Integer, PA_Integer}, {NB_Integer, PB_Integer}] :=		
	Module[ {cap, T = 1},
		If[ PA <= 2 || PB <= 2, Return[0]]; (* Prevent division by zero. *)
		cap = MemoryCapacity[{NA, PA}, {NB, PB}];
		While[T < PA && cap^2 * Binomial[PA, T] Binomial[NA - PA, PA - T] / 
			Binomial[NA, PA] >= 1, T++]; 
		T
		]																			


OverlapProbability[n_, {p1_, p2_}, v_] := 
	N[Binomial[p1, v] * Binomial[n - p1, p2 - v] / Binomial[n, p2]]


OverlapProbability[n_, p_, v_] := 
	N[Binomial[p, v] * Binomial[n - p, p - v] / Binomial[n, p]]


(* General-purpose SHR encoder/decoder for symbolic expressions. *)

codec[{n_Integer, p_Integer}] := 
	codec[{n, p}] = Module[ {self, lexicon, T},

	(* Use the auto-associative pattern matching threshold. *)
	T = MatchingThreshold[ {n, p}, {n, p}]; 

	lexicon = <| Null -> {} |>;
	self = Unique[];
	
	self["label"] = "SYM";

	self["encode"][list_List] := 
		Union[Flatten[self["encode"] /@ list]]; (* Bundle multiple tokens *)
		
	self["encode"][expr_ : Null] := 
		If[MissingQ[lexicon[expr]], 
			lexicon[expr] = Sort[RandomSample[Range[n], p]], lexicon[expr]];

	self["decode"][list_List] :=  Module[ {result, overlaps},
		If[list === {}, Return[Null]];
		(* 
		This effectively implements an auto-associative memory for sets.
		A more scalable version would use an item memory for cleanup and
		a hash-based lookup for decoding.
		*)
		overlaps = Map[ Length[Intersection[#, list]]&, lexicon];

		(* Find all matches within the auto-associative matching threshold *)
		result = Keys[Select[overlaps, # >= T &]];
				
		Switch[ Length[result],
			0, Null,
			1, First[result],
			_, result]
		];
				
	self[Clear] := lexicon = <| Null -> {} |>; (* Do not clear the unique symbol. *)

	self
	]


(* 
Random category encoder.
Generates non-overlapping SHRs for k classes.
*)

category[{n_Integer, p_Integer}, k_Integer] := 
	category[{n, p}, k] = Module[ {self, lexicon, T, partitionsize},

	lexicon = <| Null -> {} |>;
	self = Unique[];
	T = MatchingThreshold[{n, p}, {n, p}];
	
	If[ k*p > n, Message[Circuit::category, k*p]];
	
	partitionsize = Floor[n / k];
	
	self["label"] = "CAT";

	self["encode"][Null] := {};
	
	self["encode"][i_Integer] := Module[ {},
		
		If[i < 0 || i >= k, Return[{}]]; (* User error. *)
		
		If[MissingQ[lexicon[i]], 
			lexicon[i] = partitionsize i + Range[partitionsize]];
		Sort[RandomSample[lexicon[i], UpTo[p]]]
		];
		
	(* Same decoding logic as in the codec[] module above. *)
	self["decode"][list_List] :=  Module[ {result, overlaps},
		If[list === {}, Return[Null]];
		overlaps = Map[ Length[Intersection[#, list]]&, lexicon];
		result = Keys[Select[overlaps, # >= T &]];
		Switch[ Length[result],
			0, Null,
			1, First[result],
			_, result]
		];
		
	self[Clear] := lexicon = <| Null -> {} |>; 
		(* Do not clear the unique symbol. *)

	self
	]


(* 
Clustering algorithm / decoder for sets. Assigns bin numbers 1,2,...
to every new cluster found.
*)

binning[{n_Integer, p_Integer}] := 
	binning[{n, p}] = Module[ {self, lexicon, T},

	lexicon = <| Null -> {} |>;
	self = Unique[];
	T = MatchingThreshold[{n, p}, {n, p}];
	
	self["label"] = "BIN";

	self["encode"][_] := (Message[Circuit::decoder, binning]; {});
		
	self["decode"][list_List] :=  Module[ {bins, overlaps},
		If[list === {}, Return[0]];
		overlaps = Map[ Length[Intersection[#, list]]&, lexicon];
		bins = Keys[Select[overlaps, # >= T &]];
		Switch[ Length[bins],
			0, lexicon[ bins = Length[lexicon] ] = list;bins,
			1, First[bins],
			_, bins]
		];
		
	self[Clear] := lexicon = <| Null -> {} |>;
	(* Do not clear the unique symbol. *)

	self
	]


(* General SDR encoder for dense vectors. Works for any dense input. *)

vectorencoder[{n_Integer, p_Integer}, spars_:Automatic] := 
	vectorencoder[{n, p}, spars] = Module[ {self, R = <||>},

	self = Unique[];

	self["label"] = "VEC";
	
	self["encode"][list_] := Module[ {d, sparsity, vec, min, max, span, 
					scale, tolerance = 1.*^-10},

		d = Length[list];
		If[p <= 0 || d == 0, Return[{}]];
		
		sparsity = If[NumberQ[spars], N[spars], 
			N[1/Sqrt[d]]]; (* Johnson-Lindenstrauss *)
		
		(* Lazy initialization of random sparse binary matrix. *)
		If[ MissingQ[R[d]], 
			R[d] = SparseArray[(QuotientRemainder[
				RandomSample[Range[n*d], Round[n*d*sparsity]]-1, d] + 1) -> 1,
				{n, d}]
			 ];

		vec = R[d] . list;
			
		(* Compute kWTA using rank p. *)
		(* Here we make no assumption about the bounds of the input data. *)
		{min, max} = MinMax[vec];
		span = max - min;
		scale = Max[Abs[min], Abs[max]];

		(* General-purpose dead switch. *)
		(* Reject if the array is zeros, or if the span is tiny relative 
			to the overall scale. *)
		If[scale == 0 || span <= tolerance * scale, Return[{}]];
		
		(* Standard kWTA *)
		Sort[Ordering[vec, -Min[p, Length[vec]]]]
		(* Note: This selects elements strictly in the original order,
		which may introduce a bias in certain datasets. *) 

		];
		
	self["decode"][_] := Message[Circuit::encoder, vectorencoder];

	self[Clear] := R = <||>; (* Do not clear the unique symbol. *)
	
	self
	]


(* Flyhash algorithm. *)

flyhash[{n_Integer, p_Integer}, sparsity_: 0.1] := 
  flyhash[{n, p}, sparsity] = 
		Module[{self, R = <||>,  restingpotential = <||>},
    
    self = Unique[];
    
	self["label"] = "FLY";
    
    self["encode"][list_] := 
		Module[{d, c, centeredlist, vec, indices, min, max, span, 
					scale, tolerance = 1.*^-10},
     
		d = Length[list];
		If[p <= 0 || d == 0, Return[{}]];
     
		(* Input centering. Removes baseline firing magnitude. *)
		centeredlist = list - Mean[list];
     
		(* Fixed fan-in projection matrix. *)
		If[MissingQ[R[d]],
      
			(* The number of glomeruli each Kenyon cell samples from. *)
			c = Max[1, Round[d * sparsity]]; 
      
			(* Generate c distinct random column indices for each row. *)
			indices = Flatten[Table[{i, j}, {i, n}, 
				{j, RandomSample[Range[d], c]}], 1];
      
			(* Fixed biological resting potential, as static tie breaker. *)
			R[d] = SparseArray[indices -> 1, {n, d}];
			restingpotential[d] = RandomReal[{0, tolerance * 0.01}, n];
			];
     
		(* Pass signal, add the static resting potential to break ties. *)
		vec = R[d] . centeredlist + restingpotential[d];     
      
		(* General-purpose dead switch *)
		{min, max} = MinMax[vec];
		span = max - min;
		scale = Max[Abs[min], Abs[max]];
		If[scale == 0 || span <= tolerance * scale, Return[{}]];
     
		(* The APL neuron. Calculate standard kWTA. *)
		Sort[Ordering[vec, -Min[p, Length[vec]]]]
		];

	self["decode"][_] := Message[Circuit::encoder, flyhash];

	self[Clear] := R = <||>; (* Do not clear the unique symbol. *)
    
    self
  ]


(* 
At the beginning of each cycle, external input is pushed 
into the input nodes' output slots.
A network may contain multiple input nodes.
Input nodes have no callback function and no input slots.
Input data can be excitatory or inhibitory, or a mix.
*)
	
input[_Association, __] := 
	<| "size" -> Small, "checks" -> {"input", "oneout"},
		"encode" -> Identity |>;

input[enc_Symbol, opt_Association, send_, receive_] := 
	input[enc[], opt, send, receive];

input[enc_[args___], opt_Association, send_, receive_] := Module[ {c},
	c = enc[First[send], args];
	<| "label" -> c["label"], "encode" -> c["encode"], "clear" -> c, 
		"size" -> Small, "checks" -> {"input", "oneout"} |> 
	];


(* 
At the end of each cycle, this node's input edges are read out.
A network may contain multiple output nodes.
Output nodes have no callback function and no output slots.
Output data can be excitatory or inhibitory, or a mix.
*)

output[_Association, __] :=  <| "size" -> Small,  
	"checks" -> {"oneinp", "output"}, "decode" -> Identity |>;

output[dec_Symbol, opt_Association, send_, receive_] := 
	output[dec[], opt, send, receive];
		
output[dec_[args___], opt_Association, send_, receive_] := Module[ {c},
	c = dec[First[receive], args];
	<|"label" -> c["label"], "decode" -> c["decode"], "clear" -> c, 
		"size" -> Small, "checks" -> {"oneinp", "output"} |> ];


(*
A delay node encapsulates five functions in one node:

- block coding
- signal delay
- proportional decimation by a factor D     (default: 1)
- rate limiting to max population R         (default: Infinity)
- temporal integration of C elements        (default: 0)

Multisets and inhibitory signals are handled transparently. 
Temporal integration resolves inhibition.
*)

delay[opt_Association, send_, receive_] := 
	Module[ {f, n, p, dims1, dims2, decimation, 
			ratelimit, capacity, Y = {}, label = ""},

	{n, p} = First[send]; 

	dims1 = First /@ receive;
	dims2 = First /@ send;

	(* Proportional stochastic subsampling for memory query. *)
	decimation = Lookup[opt, "D", 1];
	(* Limit size of query pattern. Default: unlimited. *)			
	ratelimit  = Lookup[opt, "R", Infinity];
	(* Temporal capacity, carry over from previous cycle. *)
	capacity = Lookup[opt, "C", 0];				

	(* Visualization. *)
	If[decimation < 1, label = "D"];	
	If[ratelimit < Infinity, label = label <> "R"];	
	If[capacity > 0, label = label <> ".."];	

	f[inp__List] := Module[ {X},
		
		X = MultisetBlockJoin[ {inp}, dims1];
		
		(* X may be a mix of excitatory and inhibitory elements. 
			We let both fade at the same rate. *)
		If[decimation < 1,  (* This may result in an empty list. *)
			X = Sort[RandomSample[X, Floor[decimation Length[X]]]]]; 

		(* Rate limiting equally applies to positive and negative elements *)
		If[Length[X] > ratelimit, X = Sort[RandomSample[X, ratelimit]]]; 
		
		Y = RandomSample[Y, UpTo[capacity]]; 
		X = Multiset[X, Y]; (* Temporal integration. *)
		Y = X; (* Persist state. *)
		
		Sequence @@ MultisetBlockSplit[X, dims2]
		];

	<| "function" -> f, "checks" -> {"arginp", "argout", "totaldim"},
		"fill" -> 13, "label" -> label |>	
	]


(* 
A sample-and-hold latch with threshold and expiration.
Latches onto a signal if its population meets threshold T.
Holds and broadcasts the state for up to W additional cycles.
*)

latch[opt_Association, send_, receive_] := 
	Module[ {f, dims1, dims2, threshold, window, state, timer},

	dims1 = First /@ receive;
	dims2 = First /@ send;

	(* Hyperparameters *)
	(* Must have at least 1 element to latch by default. *)
	threshold = Lookup[opt, "T", 1]; 
	
	(* Default window is Infinity. *)
	window = Lookup[opt, "W", Infinity];
	
	(* Internal state and age tracker *)
	state = ConstantArray[{}, Length[dims2]];
	
	(* Start in an expired state. 
	If window is Infinity, Infinity + 1 simply evaluates to Infinity.
	*)
	timer = window + 1; 

	f[inp__List] := Module[ {X},
		
		X = MultisetBlockJoin[ {inp}, dims1];
		
		(* Event-driven latch: Update state if threshold is met. *)
		If[Length[X] >= threshold, 
			state = MultisetBlockSplit[X, dims2];
			timer = 0,
			
			(* Sub-threshold input: tick the timer only if within bounds. *)
			If[timer <= window, timer++];
			
			(* Check expiration. W=1 means the lifespan of the signal is 1. *)
			If[timer >= window,
				state = ConstantArray[{}, Length[dims2]]
			]
		];

		Sequence @@ state
		];

	<| "function" -> f, "checks" -> {"arginp", "argout", "totaldim"},
		"fill" -> 13, "label" -> "\[FilledRectangle]", "size" -> 17 |>	
	]


(* 
KWTA computed for multisets across multiple input slots.
Integrates time-bounding (cycles) and space-bounding (capacity).
Filters sparse signals below a minimum population threshold.

Note about the source of multisets: A single input pathway may already carry
a multiset ("+" modifier), or receive a multiset through pathway merging.
*)
	
kwta[opt_Association, send_, receive_] := 
	Module[ {f, dims1, dims2, k, cutoff, cycles, capacity, threshold, 
		window},

	dims1 = First /@ receive;
	dims2 = First /@ send;
	
	(* k is the population of the output channel. *)
	k = send[[1,2]]; 
	
	(* Temporal and space bounding parameters *)
	cycles    = Lookup[opt, "W", 1];
	capacity  = Lookup[opt, "C", Infinity];
	threshold = Lookup[opt, "T", 0];
	
	(* Minimum number of occurrences. Acts as a high-pass filter. *)			
	cutoff = Lookup[opt, "cutoff", 2];
		
	window = ConstantArray[{}, cycles];
	
	f[inp__List] := Module[ {X, U, tally, rankedmax, winners = {}}, 

		X = MultisetBlockJoin[ {inp}, dims1];

		(* Sub-threshold input: do not advance window, emit empty sets. *)
		If[Length[X] < threshold, 
			Return[Sequence @@ ConstantArray[{}, Length[dims2]]]
		];

		(* Event-driven window update: X is known to be >= threshold *)
		window = Rest[window];  AppendTo[window, X];
		
		(* Aggregate all positive elements from the current window *)
		U = Multiset[window]; 
		
		(* Capacity bounding: Unbiased subsampling if capacity is exceeded. *)
		If[Length[U] > capacity,  U = Sort[RandomSample[U, capacity]]];
			
		(* KWTA consensus on the surviving elements *)
		tally = SortBy[Tally[U], Last]; 
		
		If[ Length[tally] >= k, 
			rankedmax = tally[[-k, 2]];
			If[rankedmax >= cutoff,
				winners = Sort[Select[tally, Last[#] >= rankedmax &][[All, 1]]]]
			];
		
		Sequence @@ MultisetBlockSplit[winners, dims2]
		];
		
	<| "function" -> f, "checks" -> {"arginp", "argout", "totaldim"}, 
		"label" -> "k", "fill" -> 13 |>
	]


(* Plug-in mechanism for update rules. *)

replacement[y_,x_]   := y;
residual[y_, x_]     := Complement[x, y];
complement[y_, x_]   := Complement[y, x];
difference[args__]   := SymmetricDifference[args];
augmentation[args__] := Union[args];
coincidence[args__]  := Intersection[args];



(* 
Auto-associative memory component. 

Note: There is a wide range of possible learning, subsampling, retrieval 
and update rules for auto-associative memory. This prototype captures the 
geneneric cases. Modify as needed.
*)

auto[updaterule_: replacement, opt_Association, send_, receive_] := 
	Module[ {f, dims, p, M, label, size, min, max, 
		 ratelimit, decimation},
			
	dims = First /@ receive;
	p = Last[Plus @@ receive];

	{label, size} = 
		Switch[ updaterule, 
			replacement,  {"\[FilledDownTriangle]", Large   },
			residual,     {"\[FilledUpTriangle]", Large   },
			complement,   {"\[EmptyDownTriangle]", Large   },
			difference,   {"\[EmptyUpTriangle]", Large   },
			augmentation, {"\[Union]", Medium  },
			coincidence,  {"\[Intersection]", Medium  },
			_,            {ToString[updaterule],  Small   } (* User plug-in *)
		];

	(* Limit size of query pattern. Default: unlimited. *)			
	ratelimit  = Lookup[opt, "R", Infinity];
	(* Proportional stochastic subsampling for memory query. *)
	decimation = Lookup[opt, "D", 1];
	
	(* Learning thresholds. These apply to the total state, aggregated
	from all blocks. Modify this logic as needed. *)
	min = max = p; (* defaults *)
	If[ IntegerQ[opt["L"]], min = max = opt["L"] ];
	If[ MatchQ[opt["L"], {_Integer,_Integer}], {min, max} = opt["L"]];
	
	(* Memory with identical input and output parameters. *)
	M = Memory[#, #, 
		Threshold -> Lookup[opt, "T", Automatic]]& [Plus @@ receive];
		
	f[blocks__List] := Module[ {A, X, Y, Xdec},

		(* Join partitions and apply inhibition. *)
		A = X = ResolveBlockJoinNormal[{blocks}, dims];
		
		(* Limit the rate of incoming positives. *)
		If[Length[X] > ratelimit, X = Sort[RandomSample[X, ratelimit]]];

		(* Note: Proportional decimation may result in an empty list. *)
		Xdec = If[decimation < 1, 
			Sort[RandomSample[X, Floor[decimation * Length[X]]]], X];
				

		(* Always learn if "L"->True. Typically used for hyperassociations. *)
		If[opt["L"], M[A -> A]];

		(* Memory retrieval with decimated and rate-limited input state. *)
		Y = M[Xdec];

		(* Learn input A if retrieval fails *)
		If[Y === {} && Length[A] >= min && Length[A] <= max,
				If[opt["L"] =!= True, M[A -> A]]; Y = A];

		X = updaterule[Y, X]; 

		Sequence @@ MultisetBlockSplit[X, dims] 
		]; 
	
	<| "function" -> f, "checks" -> {"arginp", "argout", "ident"}, 
		"label" :> label, "size" -> size, "clear" -> M,
	    "shape" -> "Square", "fill" -> 8 |>
	]


(* 
Vanilla hetero-associative node for supervised learning A -> B.
B is the first input argument.
A is given by the rest of the input arguments. Can be block-coded.
Always learns if B =!= {}.
*)

associator[opt_Association, send_, receive_] := 
	Module[ {f, Adims, M, decimation, oversampling},

	Adims = First /@ Rest[receive]; (* Dimensions of input blocks A *)

	(* Proportional stochastic subsampling for training.  *)
	decimation = Lookup[opt, "D", 1];
	(* Proportional stochastic oversampling for training.  *)
	oversampling = Lookup[opt, "O", 1];
	
	(* Memory instance: *)
	M = Memory[Plus@@Rest[receive], First[send], 
				Threshold -> Lookup[opt, "T", Automatic]];

	f[B_List, A__List] := Module[{X, Y},
		
		(* Apply and drop inhibitory elements. *)
		X = ResolveBlockJoinNormal[{A}, Adims];
		Y = ResolveNormal[B];
		
		If[Y === {}, Return[ M[X]]]; (* Test. *)
		
		(* Train. Optionally apply noise to avoid overfitting. *)
		If[decimation < 1, 
			X = Sort[RandomSample[X, Floor[decimation * Length[X]]]]];

		If[oversampling > 1, 
			X = Union[X, RandomSample[Range[Length[X], Round[(oversampling-1)
					 * Length[X]]]]]];

		M[X -> Y]; 
		{}	
		];   
		
	<| "function" -> f, "checks" -> { "dimfirst", "oneout"}, "clear" -> M,
		"shape" -> "Square", "fill" -> 11, "size"-> (FontSize -> 18),
		"label"-> "\[FilledRightTriangle]\[FilledCircle]" |>
	]


(* 
Heteroencoder A -> B. A may be partitioned. Has no input for B.
*)

heteroencoder[opt_Association, send_, receive_] := 
	Module[ {f, dims, M},
	
	dims = First /@ receive;
	
	M = Memory[ Plus @@ receive, First[send], 
					Threshold -> Lookup[opt, "T", Automatic]];
	
	f[inp__List] := Module[{X, Y},
		X = ResolveBlockJoinNormal[{inp}, dims];
		(* Retrieve. *)
		Y = M[X];
		
		(* Generate new SHR encoding if retrieval fails. *)
		If[Y === {}, 
			Y = Sort[RandomSample[Range[#1], #2]]& @@ First[send]];
		
		(* Always learn, broadening X as an attractor. *)
		M[X -> Y];
			
		Y
		]; 
	
	<| "function" -> f, "checks" -> {"arginp", "oneout"}, "clear" -> M,
		"shape" -> "Square",  "fill" -> 11,  "size"-> (FontSize -> 18),
		"label" -> "\[FilledLeftTriangle]\[FilledRightTriangle]" |>
	]


(*
Generates a prediction based on the current input (slot #1) 
and context (slots #2,...).
Automatically learns the correct prediction in the following cycle.
To do so, the node remembers its context from the previous cycle.
*)

predictor[opt_Association, send_, receive_] := 
		Module[ {f, M, X = {}, prediction = {}, itemconfig, contextconfig},

	itemconfig = First[receive];
	contextconfig = Rest[receive]; (* Context may be partitioned *)
	
	M = Memory[Plus @@ contextconfig, itemconfig,
		Threshold -> Lookup[opt, "T", Automatic]]; 
	
	f[item_List, context__List] := Module[{Y},
	
		Y = ResolveNormal[item];
		
		(* State X and prediction from previous cycle *)
		(* Always learn. Also when the prediction was correct. *)
		M[X -> Y];
		
		X = ResolveBlockJoinNormal[ {context}, First /@ contextconfig];

		prediction = M[X]
		]; 

	<| "function" -> f, "checks" -> {"dimfirst", "oneout"}, "clear" -> M,
		"shape" -> "Square", "fill" -> 11, "size"-> (FontSize -> 18),
		"label" -> "\[FilledRightTriangle]\[FilledRightTriangle]"
		|>
	]


(* 
Embedded circuit, encapsulated within a component.
*)
	
circuit[arg_, opt_Association, send_, receive_] := Module[ {f, subnet, label},
	
	subnet = If[ Head[arg] === Symbol, arg, Circuit[arg]];
	
	If[ {receive, send}  =!= {subnet[In], subnet[Out]},
		Message[Circuit::embedded, {subnet[In], subnet[Out]}]];
	
	(* Skip encoding, decoding, preprocessing, and postprocessing *)
	f[inp__] := Sequence @@ subnet[Function, {inp}]; 
	
	<| "function" -> f, "checks" -> {"arginp", "argout"}, "clear" -> subnet,
		"shape" -> "Square", "size" -> Small, "label" -> ToString[subnet] |>
	]	


(* 
Random noise generator
*)
	
noise[opt_Association, send_, receive_] := Module[ {f},
	f[inp___] := Sort[RandomSample[Range[#1], #2]]& @@ First[send]; 
	
	<| "function" -> f, "checks" -> {"input", "oneout"}, "label" -> "~",
		"fill" -> 13, "size" -> 18 |>
	]	


(* Dataflow tags and their JSON names. *)
Circuit`TagMap = <|

"multiset"        -> "+", (* only multisets may contain negatives *)
"inhibit"         -> "-", (* if - then automatically + *) 
"permute"         -> "P", (* permuation, unique per pathway *)
"noise"           -> "~", (* random noise if empty, else clear elements *)
"rate_limit"      -> "R", (* stochastic rate limiting up to hyperparameter P *)
"threshold"       -> "T", (* clearing data below hyperparameter population P *)
"veto"            -> "X", (* clears all paths if any X path is non-empty *)
"mandatory"       -> "*", (* clears all paths if any * path is empty *)
"priority"        -> "!", (* clears all non-! paths if any ! path is non-empty *) 
"dependency"      -> "&", (* clears & paths if any non-& path is empty (AND) *)
"fallback"        -> "|", (* clears | paths if any non-| path is non-empty (NOR) *)
"barrier"         -> "=", (* clears = paths if any = path is empty *)
"kwta_excitatory" -> "K", (* top-k of positives *)
"kwta_absolute"   -> "k", (* top-k of all elements *)
"log"             -> "?", (* runtime log of path contents *)
"show_slot"       -> "#", (* visualization modifiers *)
"show_dimension"  -> "$", (* N *)
"show_population" -> "%"  (* P *)

|>;

(* Note: temporal gating @... is handled separately. *)


Circuit[dataflow_List] := Module[ 

	{ self, evaluate,
	permutations = <||>, 
	inputslots = {}, encoders = {}, preprocess = {},
	outputedges = {}, decoders = {}, postprocess = {},
	circuitoptions, hyperparams,
	nodes = <||>, tails = <||>, graphvertices = {},
	edgebuffer = <||>, slotbuffer = <||>, pathtags = <||>,  
	nodecount = 1, edgecount = 1, tick = 0,
	makenode, patheval},
	
	self = Unique["c"];
	
	(* Expose this circuit's input and output configurations. Needed
	 by an enclosing circuit to check interface validity. *)
	self[In] = self[Out] = {};
					
	makenode[ component_Symbol[label_String: None, args___, useropts___Rule]
					[send___][receive___] ] :=
		Module[ {id = nodecount++, opt, 
				callback, parseedge, parsefunction, fillparams, 
				inpaths, inslots, outslots, settings, 
				sendparams, receiveparams}, 
		
		(* Parse preprocessing (input receive) 
			and postprocessing (output send) function. *) 
		parsefunction[x___] := 
			If[ Length[{x}] == 1 && MatchQ[x, _Symbol | _Function | 
				_Association | _InterpolatingFunction | _CompiledFunction], 
					First[{x}],
				If[ Length[{x}] > 0, Message[Circuit::extfunc, 
					component[x]]];  Identity];		

		fillparams[rec : {___}] := Module[ {replace, result},
			(* 
			Replaces the "receive" sequence with  hyperparameters (N,P}
			{a} is a list of integers or lists of integers. 
			A list of integers denotes path merging.
			*)
			
			replace[s_Integer] := hyperparams[s];

			replace[s : {_Integer ..}] :=  Module[{params, dims},
            
				params = hyperparams /@ s;
				dims = params[[All, 1]];
            
				(* Ensure all dimensions are identical. *)
				If[SameQ @@ dims,
					{dims[[1]], Min[params[[All, 2]]]},
					(* Mismatched dimensions. *)
				   Message[Circuit::dimbundle, component]; {}]
				];

			replace[___] := (Message[Circuit::routing, rec]; {});
			
			result = replace /@ rec;
			
			If[ ! MatchQ[ Flatten[result],  {___Integer}], 
				Message[Circuit::routing, rec]; result = {} ];
			
			result
			];
				
		settings = {useropts};
		If[ StringQ[label], AppendTo[settings, "label" -> label]];
		
		(* 
		Append a counter (format "\[BeamedSixteenthNote]7") to each tag to make all edges unique.
		This is necessary because edges are used as association keys.
		These counters are not displayed.
		The "\[BeamedSixteenthNote]" marker is unlikely to collide with user labels.
		*)
		parseedge[a_List] := parseedge /@ a;
		parseedge[i_Integer] := parseedge[i * ""];
		
		(* 
		Hack: integer times string
		*)
		parseedge[(i_Integer : 1) * str_String] := 
			Module[{tags = str, mods, flags, edg, tempgates},
		
			(* Extract modifiers: everything after the first space *)
			mods = If[StringContainsQ[tags, " "], 
					Last[StringSplit[tags, " ", 2]], tags];
							
			(* Helpful compiler: If "-" but no "+", append "+" *)
			If[StringMatchQ[mods, "*-*"] && !StringMatchQ[mods, "*+*"],
				mods = mods <> "+"; tags = tags <> "+"];
		
			flags = AssociationMap[StringContainsQ[mods, #]&, 
					Values[Circuit`TagMap]];		
						
			(* Tags of the form "@10010" indicate temporal gating. *)
			tempgates = StringCases[mods, RegularExpression["@[01]+"], 1];
			If[ Length[tempgates] == 1, 
				flags["tempgates"] = 
					(# === "1")& /@ Characters[StringDrop[mods,1]]];
		
			edg = DirectedEdge[i, id, 
				StringReplace[tags, 
					{   "#" -> ToString[i], (* slot *)
						"$" -> ToString[hyperparams[i][[1]]], (* N *)
						"%" -> ToString[hyperparams[i][[2]]]  (* P *)
						}]
				 <> "\[BeamedSixteenthNote]" <> ToString[edgecount++]];
				 
			pathtags[edg] = flags;	 
			edg	 
			];		
		
		inpaths = If[ component === input,
			AppendTo[preprocess, parsefunction[receive]]; {},
			parseedge[{receive}]
			];

		inslots  = inpaths /. DirectedEdge[i_, __] :> i;
		
		outslots = If[ component === output,
			AppendTo[postprocess, parsefunction[send]]; {},
			Flatten[{send}]
			];
		
		(* Initialize edgebuffer. *)
		(edgebuffer[#] = {}) & /@ Flatten[inpaths];
		
		(* Register vertices for graph visualization. *)
		AppendTo[graphvertices, inpaths];
	
		(* Check for duplicate output slots. *)
		If[ KeyExistsQ[tails, #], Message[Circuit::dupedge,#] ]& /@ outslots;			

		(* Register backlinks from input slots to nodes. *)
		(tails[#] = id)& /@ outslots;

		(* Register and initialize slots. *)
		(slotbuffer[#] = {})& /@ Union[inslots, outslots];
		
		(* Per-node evaluation *)
		callback := Module[ {f, x, result},
			(* Node-specific callback function *)
			f = opt["function"];
			(* Input and output nodes are not evaluated. *)		
			If[f === Null, Return[]];
			(* Latch inputs. *)
			x = patheval /@ inpaths;
			(* This component's callback function. *)
			result = f[Sequence @@ x]; 
			(* Copy results to output slot. *)
			MapIndexed[(slotbuffer[#1] = {result}[[First[#2]]]) &, outslots];
			];
		
		sendparams = fillparams[outslots];
		receiveparams = fillparams[inslots];
		
		(* Base configuration for each node. 
		 Includes per-node user settings. Cannot be overridden. *)
		opt = <|  "eval" :> callback, "node" -> component, settings |>;

		(* Instantiate the component. *)
		opt = Join[component[args, opt, sendparams, receiveparams ], opt];

		(* Static error checking. *)
		If[ ! Circuit`check[#][receiveparams, sendparams], 
			Message[MessageName[Circuit, #], 
				component[args, settings][send][receive]]] & /@ opt["checks"];

		(* Prepend default visualization settings. *)
		opt = Join[<|  "shape" -> "Circle", "label" -> "", "fill" -> 6, 
			"color" -> 0, "size" -> Medium  |>,   opt];

		(* Prepend default functional settings. *)
		opt = Join[<| "checks" -> {}, "function" -> Null |>,   opt];

		(* Register input slots and output edges.
			 Indexed in order of appearance in the dataflow spec.  *)
		If[component === input,  
			AppendTo[inputslots, First[outslots]];
			AppendTo[encoders, opt["encode"]];
			AppendTo[self[In], First[sendparams]];
			opt["label"] //= StringReplace["#" -> ToString[Length[inputslots]]]
			];

		If[component === output, 
			AppendTo[outputedges, First[inpaths]];
			AppendTo[decoders, opt["decode"]];
			AppendTo[self[Out], First[receiveparams]];
			opt["label"] //= StringReplace["#" -> ToString[Length[outputedges]]]
			];
				
		nodes[id] = opt;
		];
	
	(* Parse per-slot hyperparameter settings. In the dataflow spec, these are
	 given by rules. The default rule looks like "_ -> {1000,10}" *)

	circuitoptions = Association @ Select[dataflow, Head[#] === Rule &];
	
	(* 
	Hyperparameters (N, P} for the slots are given as rules:
	7 -> {1000, 10}   // parameters for slot 7
	_ -> {1000, 10}   // default parameters
	*)
	
	hyperparams[slot_Integer] := Module[{np},
		np = Lookup[circuitoptions, slot, circuitoptions[_]];
		If[ !MatchQ[np, {_Integer, _Integer}], 
				Message[Circuit::noparam, slot]; {3, 3}, np]
		(* Default to {3, 3} to silence downstream error messages. *)
		];
	
	Scan[makenode, dataflow]; (* Construct association for each node. *)
	
	(* 
	Apply permutation, rate limit, inhibition, etc.
	
	During each cycle, this is applied once per edge: 
	Either when evaluating the callback function, or when collecting 
	outputs (output nodes have no callback function). 
	*)
	patheval[edge : DirectedEdge[a_, b_, tags_String]] := 
		Module[ {perm, x, flags, tempgates, n, p},
		
		{n, p} = hyperparams[a];
		
		x = edgebuffer[edge];
		
		(* Runtime check. *)
		If[! VectorQ[x, IntegerQ] || MemberQ[x, 0], 
			Message[Circuit::integer, x]; Return[{}]];
		
		flags = pathtags[edge];
		
		(* Process temporal gating (tags of the form @10101). *)
		tempgates = Lookup[flags, "tempgates", {True}];
		If[ ! tempgates[[Mod[tick-1, Length[tempgates]] + 1]], Return[{}]];
		
		(* 
		Inhibition transformer. Flips positives to negatives.
		This is the ONLY source of inhibition. 
		Normal pathways apply inhibitory elements and then
		drop them. This enforces Dale's law. 
		*)
		If[flags["-"], x = -Abs[x]];
		
		(*
		Carrier: forward resolved multiset.
		Boundary: untagged edges force resolution to a flat, excitatory set. 
		*)
		x = If[flags["+"], Multiset[x], ResolveNormal[x]];

		(* Permutation. *)
		If[flags["P"],   
			If[ Head[perm = permutations[edge]] === Missing, 
				(* Lazy initialization. *)
				permutations[edge] = perm = RandomSample[Range[n]]];
			(* Extract absolute IDs, permute them, and restore the signs. *)			
			x = Sort[Sign[x]*perm[[Abs[x]]]] ];
	
		(* Rate limiting. *)
		If[flags["R"], x = Sort[RandomSample[x, UpTo[p]]]];

		(* Thresholding. *)
		If[flags["T"] && Length[x] < p, x = {}];

		(* Random noise if x = {}, else clear x *)
		If[flags["~"], 
			If[ x === {}, x = Sort[RandomSample[Range[n], p]], x = {}]];

		(* Print value to console. *)
		If[flags["?"], Print["Slot ", a, ": ", x]];
						
		x
		];
		
	(* Process the "brace" notation, merging neural pathways. *)
	patheval[edges : {__DirectedEdge}] := Module[ {x, tags, merged},
		x = patheval /@ edges;
				
		tags = Function[t, Lookup[pathtags[#], t] & /@ edges];

		(* Logical gating. *)

		If[MemberQ[Pick[x, tags["X"]], {__}], Return[{}]];

		If[MemberQ[Pick[x, tags["*"]], {}], Return[{}]];

		If[MemberQ[Pick[x, tags["!"]], {__}], 
			x = MapThread[If[#1, #2, {}] &, {tags["!"], x}] ];

		If[MemberQ[Pick[x, Not /@ tags["&"]], {}], 
			x = MapThread[If[#1, {}, #2] &, {tags["&"], x}] ];
			
		If[MemberQ[Pick[x, Not /@ tags["|"]], {__}], 
			x = MapThread[If[#1, {}, #2] &, {tags["|"], x}] ];

		If[MemberQ[tags["="], True] && MemberQ[Pick[x, tags["="]], {}],
             x = MapThread[If[#1, {}, #2]&, {tags["="], x}]];

		(* Aggregate the survivors. *)
		merged = Multiset[x];
	
		(* Optional kWTA. *)
		If[MemberQ[tags["k"], True] || MemberQ[tags["K"], True],
			Module[{k, U, tally, rankedmax, excitQ, survivors},
			
				k = Min[ hyperparams[#[[1]]][[2]] & /@ edges ];
			
				(* "K" forces excitatory only. 
					"k" evaluates absolute saliency. *)
				excitQ = MemberQ[tags["K"], True];
			
				U = If[excitQ, Select[merged, # > 0 &], merged];
			
				tally = SortBy[Tally[U], Last];
			
				(* Force consensus: k elements must appear at least twice. *)
				merged = {};
				If[Length[tally] >= k,
					rankedmax = tally[[-k, 2]];
					If[ rankedmax >= 2,
						merged = Sort[Select[tally, 
								Last[#] >= rankedmax &][[All, 1]]]];
	   			]]
			];	
				
		merged
		];
			
	(* Raw evaluation cycle, operating on preprocessed and encoded data. *)
	evaluate[x_List] := Module[ {},
	
		(* Advance this circuit unit's time. *)
		tick ++;
	
		(* Push external inputs. *)
		MapIndexed[(slotbuffer[#1] = x[[First[#2]]]) &, inputslots];

		(* **Tick** *)
		
		(* Copy slot buffers into edge buffers. *)
		(* Lookup with default {} in case the edge has no source. *)
		edgebuffer = Association[
			(# -> Lookup[slotbuffer, First[#], {}])& /@ Keys[edgebuffer]];
				
		(* **Tock** *)
		
		(* Evaluate nodes, updating the slotbuffer. *)
		#["eval"]& /@ nodes;
		
		(* Update output edges. *)
		(edgebuffer[#] = Lookup[slotbuffer, First[#], {}])& /@ 
						Flatten[outputedges];

		(* Gather all outputs. *)
		patheval /@ outputedges
		];

	(* 
	The dataflow description generates this function. 
	Each call, also with empty inputs, triggers one execution cycle. 
	The function has a variable number of arguments which must match
	the number of input nodes.
	It returns a Sequence of expressions, each corresponding to an
	output node. The ordering of input and output arguments corresponds 
	to the order in which input and output nodes appear in the dataflow
	description. 	
	*)	

	self[Function, x_List] := Module[ {y, multiplex},

		(* Number of external input slots must match number of input nodes. *)
		If[ Length[x] =!= Length[inputslots], 
			Message[Circuit::sequence, inputslots]; Return[{}]];
		(* 
		Evaluate according to the "multiplex" spec, for example "10010". 
		1: evaluate with preprocessed and encoded x
		0: evaluate with empty input
		See also: temporal gating in path evaluation.
		*)

		multiplex = Lookup[ circuitoptions, "multiplex", "1"];
		If[ ! StringMatchQ[ multiplex, RegularExpression["[01]+"]],
			Message[Circuit::multiplex, multiplex]; multiplex = "1"];
		
		Do[y = If[gate === "1", evaluate[x], 
			evaluate[{} & /@ x]], {gate, Characters[multiplex]}];
		
		y
		];
			
	self[inp___] := Module[ {x, y, multiplex},
	
		(* Wrap input sequence into a list. *)
		x = {inp};
	
		(* Number of external input slots must match number of input nodes. *)
		If[ Length[x] =!= Length[inputslots], 
			Message[Circuit::sequence, inputslots]; Return[{}]];
				
		(* Preprocess. *)
		x = MapThread[Construct, {preprocess, x}];	
		(* Encode. *)
		x = MapThread[Construct, {encoders, x}];
		
		(* Multiplexed evaluation of encoded and preprocessed data *)
		y = self[Function, x];		
		
		(* Decode. *)
		y = MapThread[Construct, {decoders, y}];	
		(* Postprocess. *)
		y = MapThread[Construct, {postprocess, y}];
			
		(* Strip list, return as sequence. *)
		Sequence @@ y
		];
		
	(* Visualization. *)
	self[Graph, opts___Rule] := Module[ 
		{ graph, layout = {"LayeredDigraphEmbedding", "Orientation" -> Left},
			coords = Automatic, radius = 0.4, colorscheme, 
			font = "Inter Variable", cleantag},
			
		(* Color palette lookup. *)
		colorscheme[c_] := Lookup[ Circuit`color, c, c];
		
		(* Assign dummy slot if the user hasn't specified it. *)
		graph = MapAt[ Lookup[tails, #, -99999]&, 
			Union[Flatten[graphvertices]], {All, 1}];

		(* Remove hidden unique edge tag. *)
		cleantag[DirectedEdge[a_,b_,t_String]] := 
			Module[{tag},
				tag = StringDelete[t, {"\[BeamedSixteenthNote]"~~___}];
				If[tag === "", DirectedEdge[a, b], DirectedEdge[a, b, tag]]
				];	

		graph = cleantag /@ graph;
		
		(* Force path graphs to render on a single line. *)
		If[PathGraphQ[SimpleGraph[graph]],
			coords = (# -> {#, 0})& /@ Range[Length[nodes]]];
			
		Graph[ graph,
			PlotTheme -> "Classic",
			BaseStyle -> {FontFamily -> font, Opacity[1]},
			
			VertexSize -> radius,  
			
			VertexShapeFunction -> Normal[#["shape"] & /@ nodes],
			
			VertexStyle -> Normal[
				Directive[colorscheme[#["fill"]], 
				EdgeForm[Directive[colorscheme[1], AbsoluteThickness[0.15]]],
				Opacity[1]]& /@ nodes],

			VertexLabels -> Normal[ Placed[Style[#["label"], 
				colorscheme[#["color"]], 
				#["size"], Bold], Center]& /@ nodes],

			VertexCoordinates -> coords,

			EdgeStyle -> Normal[
				# -> Module[{tags = If[Length[#] == 3, #[[3]], ""]},

				Which[
 
				(* Multiset inhibitory (tag "-"): thick red *)
				StringMatchQ[tags, "*-*"],
				Directive[colorscheme[11], Opacity[1], AbsoluteThickness[3.5]], 
                       
				(* Multiset excitation (tag "+"): thick blue *)
				StringMatchQ[tags, "*+*"],
				Directive[colorscheme[8], Opacity[1], AbsoluteThickness[3.5]], 
            
				(* Default: dark gray and thin *)
				True,
				Directive[colorscheme[0], Opacity[1], AbsoluteThickness[0.5]]
				]] & /@ graph
				],

			EdgeLabels -> Normal[
				# -> If[Length[#] == 3,
				With[{cleanTag = StringReplace[#[[3]], 
					{"-" -> "" ,"+" -> "", "*" -> "\:ff0a"}]},
				If[cleanTag === "", 
				(* If the tag only contained hidden characters, hide it. *)
				None, 
				Placed[Framed[cleanTag, Background -> White, 
				FrameStyle -> None, 
				BaseStyle -> Directive[12, Bold, colorscheme[0]],
				RoundingRadius -> 30, FrameMargins -> 0], Center]
				]], None (* Hide labels for untagged edges. *)
				] & /@ graph],

			opts,
			GraphLayout -> layout
			]
		];	
		
	self[Clear] :=  (* Don't remove the unique symbol "self". *)	
		Scan[#[Clear]&, 
			Flatten[Values[Map[Lookup[#, "clear", Nothing]&, nodes]]]];
				
	self
	]


(* Plug-in mechanism for color palette. *)

Circuit`color = AssociationThread[Range[0,Length[#]-1],#]& [RGBColor /@ 
	{"#2E3440","#3B4252","#434C5E","#4C566A",
	"#D8DEE9","#E5E9F0","#ECEFF4","#8FBCBB",
	"#88C0D0","#81A1C1","#5E81AC","#BF616A",
	"#D08770","#EBCB8B","#A3BE8C","#B48EAD"}];


(* Plug-in mechanism for error messages. *)

Circuit::ident     = "`1`: Inputs must match outputs.";
Circuit::identdim  = "`1`: Input and output dimensions must be identical.";
Circuit::totaldim  = "`1`: Total input and output dimensions must match.";
Circuit::dupedge   = "Duplicate edge specification `1`.";
Circuit::sequence  = "`1`: Function arguments do not match input nodes.";
Circuit::routing   = "Invalid routing specification `1`.";
Circuit::dimbundle = "`1`: Cannot bundle sets with different dimensions.";
Circuit::dimfirst  = "`1`: Output must match first input slot.";
Circuit::input     = "No input slots allowed in `1`.";
Circuit::oneinp    = "Expecting one input slot in `1`.";
Circuit::arginp    = "`1`: Missing input.";
Circuit::output    = "No output slots allowed in `1`.";
Circuit::oneout    = "`1`: Expecting one output slot.";
Circuit::argout    = "`1`: Missing output.";
Circuit::multinp   = "`1`: Expecting multiple input slots.";
Circuit::integer   = "Invalid data: `1`";
Circuit::extfunc   = "`1`: Invalid external function specification.";
Circuit::embedded  = "`1`: Hyperparameters of embedded circuit do not match.";
Circuit::noparam   = "No hyperparameters specified for slot `1`.";
Circuit::category  = "Category encoder requires dimension `1` or greater.";
Circuit::encoder   = "`1` cannot be used as a decoder.";
Circuit::decoder   = "`1` cannot be used as an encoder.";
Circuit::regress   = "Regression: output should match `1`.";
Circuit::multiplex = "Malformed multiplex specification `1`.";


(* Plug-in mechanism for checking dataflow errors. *)
(* #1 is the "receive" and #2 is the "send" configuration of a component. *)

Circuit`check = <||>;

Circuit`check["ident"]    = (#1[[All,1]] === #2[[All,1]] &);
Circuit`check["identdim"] = (Union[#1[[All,1]]] === Union[#2[[All,1]]] &);
Circuit`check["totaldim"] = (Total[#1[[All,1]]] === Total[#2[[All,1]]] &);
Circuit`check["dimfirst"] = (#1[[1]] === #2[[1]] &);
Circuit`check["input"]    = (Length[#1] === 0 &);
Circuit`check["oneinp"]   = (Length[#1] === 1 &);
Circuit`check["arginp"]   = (Length[#1] > 0 &);
Circuit`check["output"]   = (Length[#2] === 0 &);
Circuit`check["oneout"]   = (Length[#2] === 1 &);
Circuit`check["argout"]   = (Length[#2] > 0 &);


(*
Usage:

dataflow = Import["filename.json", "Circuit"];
Export["filename.json", dataflow, "Circuit"];

dataflow = ImportString[str, "Circuit"];
str = ExportString[dataflow, "Circuit"];

*)


(* 
Convert dataflow expression to JSON-style association.
*)

ToCircuitJSON[dataflow_List] := 
    Module[ {rules, hyperparams = <||>, rootopts = <||>, customopts = <||>, 
         nodes, components, parsenode, parsepath, parsemerge},
    
    (* Include schema reference at the root *)
    AppendTo[rootopts, "$schema" -> "https://creatingintelligence.org/schemas/circuit-v1.json"];

    (* Extract all rules from the dataflow. *)
    rules = Select[dataflow, Head[#] === Rule &];
    
    (* Sort integers/blanks to hyperparameters, specific keys to root, and others to options. *)
    Scan[ Function[{rule}, Which[
		rule[[1]] === _, 
			AppendTo[hyperparams, "default" -> rule[[2]]],
		IntegerQ[rule[[1]]], 
			AppendTo[hyperparams, ToString[rule[[1]]] -> rule[[2]]],
        (* Core root-level schema properties *)
        MemberQ[{"version", "metadata", "$schema"}, rule[[1]]],
            AppendTo[rootopts, rule[[1]] -> rule[[2]]],
        (* Intercept and expand "multiplex" into an array of 0s and 1s inside custom options *)
        rule[[1]] === "multiplex" && StringQ[rule[[2]]],
            AppendTo[customopts, "multiplex" -> (If[# === "1", 1, 0] & /@ Characters[rule[[2]]])],
        (* Group all remaining top-level string configurations into 'options' *)
		StringQ[rule[[1]]], 
			AppendTo[customopts, rule[[1]] -> rule[[2]]],
		True, 
			AppendTo[customopts, ToString[rule[[1]]] -> rule[[2]]]
         ]], rules
		];
    
    (* Extract circuit components. *)
    nodes = Select[dataflow, Head[#] =!= Rule &];
    
    (* Helper to parse individual path strings into structured JSON objects *)
    parsepath[p_] := Module[
        {s = ToString[p], match, slot, tags, tagmap, 
            found, result = <||>, tagPattern, parts},
        
        match = StringCases[s, StartOfString ~~ n:DigitCharacter.. ~~ Whitespace... ~~ t:___ ~~ EndOfString :> {ToExpression[n], t}];
        
        If[match === {}, 
			(* Build the regex pattern dynamically from the TagMap *)
            tagPattern = (Alternatives @@ Join[Values[Circuit`TagMap], {" "}] | 
				("@" ~~ DigitCharacter..))..;
            
            If[StringMatchQ[s, tagPattern], match = {{1, s}}, Return[s]]
			];
        
        {slot, tags} = match[[1]];
        
        If[tags === "", Return[slot]];
        
        result["slot"] = slot;
        
        (* Split user label from functional tags *)
        If[StringContainsQ[tags, " "],
            parts = StringSplit[tags, " ", 2];
            result["label"] = parts[[1]];
            tags = parts[[2]]];
        
        With[{g = StringCases[tags, "@" ~~ val:(DigitCharacter..) :> val]},
            If[Length[g] > 0,
                result["gating"] = If[# === "1", 1, 0] & /@ Characters[g[[1]]];
                tags = StringReplace[tags, "@" ~~ g[[1]] -> ""]; 
            ]
        ];
        
        tagmap = Association[Reverse /@ Normal[Circuit`TagMap]];
        
        found = DeleteMissing[Lookup[tagmap, Characters[tags]]];
        
        If[Length[found] > 0, result["tags"] = found];
        
        result
    ];

    parsemerge[l_List] := parsepath /@ l;
    parsemerge[p_] := parsepath[p];

    parsenode[compExpr_[send___][receive___]] := Module[
        {comp, compName, argslist, label = Null, args = {}, opts = <||>},
        
        comp = Head[compExpr]; 
        compName = ToString[comp];
        argslist = List @@ compExpr; 
        
        Do[ Which[
           Head[arg] === Rule, AppendTo[opts, arg],
           StringQ[arg] && label === Null && args === {}, label = arg,
           True, AppendTo[args, ToString[arg, InputForm]]], {arg, argslist}
           ];
        
        DeleteCases[ <|
            "component" -> compName,
            "label" -> label,
            "arguments" -> args,
            "options" -> opts,
            "send" -> If[compName === "output", 
                         Map[ToString[#, InputForm]&, Flatten[{send}, 1]], 
                         Map[parsemerge, Flatten[{send}, 1]]],
            "receive" -> If[compName === "input", 
                            Map[ToString[#, InputForm]&, {receive}], 
                            Map[parsemerge, {receive}]]
            |>, Null | {} | <||> 
             ]
        ];

    components = parsenode /@ nodes;
    
    (* If there are grouped custom options (including multiplex), attach them under options key *)
    If[Length[customopts] > 0, AppendTo[rootopts, "options" -> customopts]];

    (* Assemble association with top-level options spread at the root. *)
    Join[rootopts, 
       <|"hyperparameters" -> hyperparams, "dataflow" -> components|>]
    ]


(* 
Convert JSON-style association to dataflow expression. 
*)

FromCircuitJSON[rawJSON_Association] := 
	Module[ {hyperparams, hprules, topoptsrules, dataflow, buildpath, 
	    buildmerge, parsenode, nodeExprs, rawOptions},

    (* Extract and merge root-level options and the inner "options" object *)
    rawOptions = Join[
        KeyDrop[rawJSON, {"hyperparameters", "dataflow", "options"}],
        Lookup[rawJSON, "options", <||>]
    ];

    (* Reconstruct top-level rules. Convert multiplex array back to string.*)
    topoptsrules = Normal @ KeyValueMap[
        Function[{k, v},
            Which[
                k === "multiplex" && ListQ[v], "multiplex" -> StringJoin[ToString /@ v],
                True, k -> v
            ]
        ],
        rawOptions
    ];

    (* Reconstruct hyperparameters. *)
    hyperparams = Lookup[rawJSON, "hyperparameters", <||>];
    hprules = KeyValueMap[
        Function[{k, v},
            Which[
                k === "default", _ -> v,
                StringMatchQ[k, NumberString], ToExpression[k] -> v, 
                True, k -> v 
            ]],
        hyperparams
		];
    
    buildpath[p_] := Module[{slot, tags = "", tagstr = "", 
               gatingStr = "", userlabel = ""},
        
        If[IntegerQ[p] || StringQ[p], Return[p]];
        
        slot = p["slot"];
        
        If[KeyExistsQ[p, "tags"],
            tagstr = StringJoin[Lookup[Circuit`TagMap, p["tags"], ""]]];
        
        If[KeyExistsQ[p, "gating"],
            gatingStr = "@" <> StringJoin[ToString /@ p["gating"]]];
        
        (* Prepend the label and a space if it exists *)
        If[KeyExistsQ[p, "label"], userlabel = p["label"] <> " "];
        
        tags = userlabel <> tagstr <> gatingStr;
        
        If[tags === "", slot, slot * tags]
    ];

    buildmerge[l_List] := buildpath /@ l;
    buildmerge[p_] := buildpath[p];

    parsenode[node_Association] := Module[
        {comp, compName, label, args, opts, send, receive, compExpr},
        
        compName = node["component"];
        comp = Symbol[compName];
        label = Lookup[node, "label", Null];
        args = ToExpression /@ Lookup[node, "arguments", {}];
        opts = Normal[Lookup[node, "options", <||>]];
        
        compExpr = comp @@ DeleteCases[
            Join[If[label =!= Null, {label}, {}], args, opts], Null];
        
        send = Sequence @@ If[compName === "output", 
                              ToExpression /@ Lookup[node, "send", {}], 
                              Map[buildmerge, Lookup[node, "send", {}]]];
                              
        receive = Sequence @@ If[compName === "input", 
                                 ToExpression /@ Lookup[node, "receive", {}], 
                                 Map[buildmerge, Lookup[node, "receive", {}]]];
        
        compExpr[send][receive]
		];

    dataflow = Lookup[rawJSON, "dataflow", {}];
    nodeExprs = parsenode /@ dataflow;

    (* Return unified dataflow list. *)
    Join[nodeExprs, hprules, topoptsrules]
	]


(* 
JSON formatting 
*)

FormatCircuitJSON[dict_Association] := Module[
    {decodeBytes, cleanString, formatrootelement, rootStrList, 
       dfStrList, dfStr},
    
    decodeBytes[s_String] := 
		If[Max[ToCharacterCode[s]] <= 255, 
			FromCharacterCode[ToCharacterCode[s], "UTF8"], s
		];
    
    (* Post-process the JSON string to add spaces and unescape forward slashes *)
    cleanString[s_String] := StringReplace[s, {
        "\":" -> "\": ", 
        "," -> ", ", 
        "\\/" -> "/"
    }];
    
    (* Format every top-level key except "dataflow". *)
    formatrootelement[k_String] := 
        "\"" <> k <> "\": " <> cleanString @ decodeBytes @ 
            ExportString[dict[k], "RawJSON", "Compact" -> True];
        
    rootStrList = formatrootelement /@ Keys[KeyDrop[dict, {"dataflow"}]];
    
    (* Compress each individual dataflow node. *)
    dfStrList = cleanString @ decodeBytes @ 
       ExportString[#, "RawJSON", "Compact" -> True] & /@ dict["dataflow"];
    
    (* Assemble the dataflow array. *)
    dfStr = "\"dataflow\": [\n    " <> 
		StringRiffle[dfStrList, ",\n\n    "] <> "\n  ]";
    
    (* Final assembly.  *)
    "{\n  " <> StringRiffle[Append[rootStrList, dfStr], ",\n\n  "] 
       <> "\n}"
	]


(* 
ImportExport framework registration and hooks                                 
*)

ImportExport`RegisterFormat["Circuit", "DefaultExtension" -> "json"];

ExportCircuitHook[channel_, data_, opts___] := 
    Export[channel, 
        FormatCircuitJSON[ToCircuitJSON[data]], "Text", 
        CharacterEncoding -> "UTF8"];
                        
ImportCircuitHook[channel_, opts___] := 
    FromCircuitJSON[Import[channel, "RawJSON"]];

ImportExport`RegisterExport["Circuit", ExportCircuitHook];
ImportExport`RegisterImport["Circuit", ImportCircuitHook];


(* -------------------------------------------------------------------------- *)
