(* ::Package:: *)

(************************************************************************)\012(* This file was generated automatically by the Mathematica front end.  *)\012(* It contains Initialization cells from a Notebook file, which         *)\012(* typically will have the same name as this file except ending in      *)\012(* ".nb" instead of ".m".                                               *)\012(*                                                                      *)\012(* This file is intended to be loaded into the Mathematica kernel using *)\012(* the package loading commands Get or Needs.  Doing so is equivalent   *)\012(* to using the Evaluate Initialization Cells menu command in the front *)\012(* end.                                                                 *)\012(*                                                                      *)\012(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)\012(* automatically each time the parent Notebook file is saved in the     *)\012(* Mathematica front end.  Any changes you make to this file will be    *)\012(* overwritten.                                                         *)\012(************************************************************************)\012\012

(*
Copyright (c) 2026 Peter Overmann
 
SPDX-License-Identifier: MIT
 
This file is part of the "Creating Intelligence" project. It is licensed 
under the MIT License. You may obtain a copy of the License in the LICENSE 
file in the root directory of this repository.
 
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR 
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, 
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
*)


<< "Memory.m"


(*
This package processes sparse sets and multisets through user-defined circuits.
Data flow is controlled by paths that connect various circuit components.
Associative memory functionality is isolated in specific types
of memory components.

Paths are either "digital" sets of integers i > 0, or "analog"
multisets of integers i > 0 for excitatory and i < 0 for inhibitory 
signals.

Partitioned multisets may be formed through the disjoint aggregation
of individual multisets. We refer to this mechanism as block coding.

All components must properly handle the presence of negative elements. 
The memory components systematically apply and then drop inhibitory 
elements, because the associative memory algorithms are inherently digital.
*)


(* 
Summates excitatory and inhibitory signals.
Outputs a net multiset. 
No element will exist as both positive and negative. 
*)

Multiset[u___List] := Module[{x, tally},

	x = Flatten[{u}];
	
	(* Tally positives, tally negatives, and add them together *)
	tally = Merge[{
				Counts[Select[x, # > 0 &]], 
				(* Shift to positive, but make counts negative. *)
				-Counts[-Select[x, # < 0 &]] 
				}, Total];
	
	(* Reconstruct the net multiset. *)
	Sort @ Flatten @ KeyValueMap[
		If[#2 == 0, 
			{}, (* Exact cancellation. *)
			(* Restore sign and multiplicity *)
			ConstantArray[Sign[#2] * #1, Abs[#2]] 
		] &, tally]
	]


(* Applies graded inhibition, drops negatives, squashes excitatory survivors. *)

ResolveNormal[x_List] := Module[{AE, AI, countsE, countsI},

	AE =  Select[x, # > 0 &];
	AI = -Select[x, # < 0 &]; 
	
	If[AI === {}, Return[Union[AE]]]; (* Fast path for pure boolean. *)
	
	countsE = Counts[AE];
	countsI = Counts[AI];
	
	Sort[Select[Keys[countsE], countsE[#] > Lookup[countsI, #, 0] &]]
	]


(* Applies graded inhibition, drops negatives, keeps excitatory survivors. *)

ResolveGraded[x_List] := Module[{AE, AI, countsE, countsI},

	AE =  Select[x, # > 0 &];
	AI = -Select[x, # < 0 &];
	
	If[AI === {}, Return[Sort[AE]]]; (* Fast path for pure multisets. *)
	
	countsE = Counts[AE];
	countsI = Counts[AI];
	
	Sort[Flatten @ KeyValueMap[
		ConstantArray[#1, Max[0, #2 - Lookup[countsI, #1, 0]]] &, 
		countsE ]]
	]


(* 
Transparently joins multisets. Preserves duplicates and negative signs. 
*)

MultisetBlockJoin[blocks : {__List}, dims : {__Integer}] := Module[{offsets},
	(* Calculate the starting index for each block *)
	offsets = FoldList[Plus, 0, Most[dims]];
	
	Flatten @ MapThread[
		Function[{sublist, offset},
			(* Shift absolute IDs to prevent collision, then restore the sign *)
			Sign[sublist] * (Abs[sublist] + offset)
		],
		{blocks, offsets} ]
	]


(* 
Transparently splits a joined multiset back into its original blocks. 
*)

MultisetBlockSplit[A_List, dims : {__Integer}] := Module[{limits, bounds},
	
	(* Calculate the ID boundaries for each block *)
	limits = FoldList[Plus, 0, dims];
	bounds = Partition[limits, 2, 1];
	
	Map[
		Function[{b},
			(* Select elements whose absolute ID falls in this block's range. *)
			Module[{chunk = Select[A, b[[1]] < Abs[#] <= b[[2]] &]},
				(* Remove the offset and restore the sign. *)
				Sign[chunk] * (Abs[chunk] - b[[1]])
			]
		], bounds ]
	]


(* 
Join blocks {A1,A2,...} with dimensions {n1,n2,...} into a single list. 
Applies graded inhibition and drops inhibitory elements. 
Preserves multisets. 
*)
MultisetBlockJoinNormal[blocks : {__List}, dims : {__Integer}] := 
	Module[ {join, signs, AE, AI, countsE, countsI, netExcitatory},

	(* Add offsets to each block to ensure disjoint ID spaces. *)
	join = Function[{x}, Flatten[x + FoldList[Plus, 0, Most[dims]]]];
	
	signs = Sign /@ blocks;
	
	(* Extract and offset excitatory and inhibitory elements. *)
	AE = join[ MapThread[  Pick[#1,#2, 1]&, {blocks, signs}]];
	AI = join[ MapThread[ -Pick[#1,#2,-1]&, {blocks, signs}]];

	(* Count frequencies for graded subtraction. *)
	countsE = Counts[AE];
	countsI = Counts[AI];
	
	(* Graded Subtraction: Excitatory count minus Inhibitory count, 
		floored at zero. *)
	netExcitatory = Flatten @ KeyValueMap[
		ConstantArray[#1, Max[0, #2 - Lookup[countsI, #1, 0]]] &, 
		countsE
		];
	
	(* Return the surviving excitatory multiset. Negatives are dropped. *)
	Sort[netExcitatory]
	]


(*
Applies graded subtraction, drops negatives, and squashes the survivors. 
Outputs a flat, Boolean excitatory set.
*)

ResolveBlockJoinNormal[blocks: {__List}, dims : {__Integer}] := 
	Module[{join, signs, AE, AI, countsE, countsI, survivors},

	(* Add offsets to each block to ensure disjoint ID spaces *)
	join = Function[{x}, Flatten[x + FoldList[Plus, 0, Most[dims]]]];
	signs = Sign /@ blocks;
	
	(* Extract and offset excitatory and inhibitory elements. *)
	AE = join[MapThread[  Pick[#1,#2, 1]&, {blocks, signs}]];
	AI = join[MapThread[ -Pick[#1,#2,-1]&, {blocks, signs}]];

	(* Count frequencies for graded evaluation *)
	countsE = Counts[AE];
	countsI = Counts[AI];
	
	(* Squash: An element survives only if excitation  exceeds inhibition. *)
	survivors = Select[Keys[countsE], countsE[#] > Lookup[countsI, #, 0] &];
	
	Sort[survivors]
	]


MemoryCapacity[{NA_, PA_}, {NB_, PB_}] := 
	If[NA == NB && PA == PB,
		(* Auto-associative. *)
		Round[ Log[2] * (NB * (NA-1) * (NA-2)) / (PB * (PA-1) * (PA-2) ) ],
		(* Hetero-associative. *)
		Round[ Log[2] * (NB * NA * (NA-1)) / (PB * PA * (PA-1) ) ]
		]


MatchingThreshold[{NA_Integer, PA_Integer}, {NB_Integer, PB_Integer}] :=		
	Module[ {cap, T = 1},
		If[ PA <= 2 || PB <= 2, Return[0]]; (* Prevent division by zero. *)
		cap = MemoryCapacity[{NA, PA}, {NB, PB}];
		While[T < PA && cap^2 * Binomial[PA, T] Binomial[NA - PA, PA - T] / 
			Binomial[NA, PA] >= 1, T++]; 
		T
		]																			


OverlapProbability[n_, {p1_, p2_}, v_] := 
	N[Binomial[p1, v] * Binomial[n - p1, p2 - v] / Binomial[n, p2]]


OverlapProbability[n_, p_, v_] := 
	N[Binomial[p, v] * Binomial[n - p, p - v] / Binomial[n, p]]


(* General-purpose SHR encoder/decoder for symbolic expressions. *)

codec[config_Association] := Module[ {f, n, p, lex, T},

	{n, p} = config["hyperparameters"];
	
	(* Create global hash table shared by all instances with
	the same hyperparameters, enabling encode-decode roundtrips. *)
	 
	lex = Circuit`codecLexicon[n, p];
	If[ ! MatchQ[ lex, _DataStructure], 
		lex = Circuit`codecLexicon[n, p] = CreateDataStructure["HashTable"]];
	lex["Insert", Null -> {} ];
	
	(* Use the auto-associative pattern matching threshold. *)
	T = MatchingThreshold[ {n, p}, {n, p}]; 

	
	f[expr_] := Module[ {result, overlaps},
	
		(* Encoding *)
		If[ config["component"] === input,

			(* Bundle multiple tokens *)
			If[MatchQ[expr, _List], Return[Union[Flatten[f /@ expr]]]];
			
			If[MissingQ[lex["Lookup", expr]], 
				lex["Insert", expr -> Sort[RandomSample[Range[n], p]]]];
				
			Return[lex["Lookup", expr]];	
			];
		
		(* Decoding *)
		If[expr === {}, Return[Null]];
		(* 
		This effectively implements an auto-associative memory for sets.
		A more scalable version would use an item memory for cleanup and
		a hash-based lookup for decoding.
		*)
		overlaps = Map[ Length[Intersection[#, expr]]&, Normal[lex]];

		(* Find all matches within the auto-associative matching threshold *)
		result = Keys[Select[overlaps, # >= T &]];
				
		Switch[ Length[result],
			0, Null,
			1, First[result],
			_, Sort[result]]
		
		];
		
	<| "label" -> "SYM", "function" -> f, "clear" :> lex["KeyDropAll"] |>
	]


(* 
Random category encoder.
Generates non-overlapping SHRs for K classes.
*)

category[config_Association] := Module[ {f, n, p, K, partitionsize, lex, T},

	{n, p} = config["hyperparameters"];
	
	(* Number of categories / classes. *)
	K = Lookup[config, "categories", Floor[n / p]];
	If[ K*p > n, Message[Circuit::category, K*p]];
	partitionsize = Floor[n / K];

	(* Create global hash table shared by all instances with
	the same hyperparameters, enabling encode-decode roundtrips. *)

	lex = Circuit`categoryLexicon[n, p];
	If[ ! MatchQ[ lex, _DataStructure], 
		lex = Circuit`categoryLexicon[n, p] = CreateDataStructure["HashTable"]];
	lex["Insert", Null -> {} ];
	
	(* Use the auto-associative pattern matching threshold. *)
	T = MatchingThreshold[ {n, p}, {n, p}]; 

	
	f[expr_] := Module[ {result, overlaps},
	
		(* Encoding *)
		If[ config["component"] === input,

			If[!IntegerQ[expr] || expr < 0 || expr >= K, Return[{}]]; 
		
			If[MissingQ[lex["Lookup", expr]], 
				lex["Insert", expr -> partitionsize*expr + Range[partitionsize]]];
			
			Return[Sort[RandomSample[lex["Lookup", expr], UpTo[p]]]];
			];
		
		(* Decoding (same as codec) *)
		If[expr === {}, Return[Null]];
		overlaps = Map[ Length[Intersection[#, expr]]&, Normal[lex]];
		(* Find all matches within the auto-associative matching threshold *)
		result = Keys[Select[overlaps, # >= T &]];
		Switch[ Length[result],
			0, Null,
			1, First[result],
			_, Sort[result]]
		
		];
		
	<| "label" -> "CAT", "function" -> f, "clear" :> lex["KeyDropAll"] |>
	]


(* 
Clustering algorithm / decoder for sets. Assigns bin numbers 1,2,...
to every new cluster found.
*)
	
binning[config_Association] := Module[ {f, n, p, lex, T},

	{n, p} = config["hyperparameters"];
	
	(* Create global hash table shared by all instances with
	the same hyperparameters, enabling encode-decode roundtrips. *)

	lex = Circuit`binningLexicon[n, p];
	If[ ! MatchQ[ lex, _DataStructure], 
		lex = Circuit`binningLexicon[n, p] = CreateDataStructure["HashTable"]];
	lex["Insert", Null -> {} ];
		
	(* Use the auto-associative pattern matching threshold. *)
	T = MatchingThreshold[ {n, p}, {n, p}]; 

	(* Decoder only *)
	If[config["component"] === input,
		Message[Circuit::decoder, binning]; Return[<||>]];
		
	f[expr_] := Module[ {bins, overlaps},
		If[expr === {}, Return[0]];
		overlaps = Map[ Length[Intersection[#, expr]]&, Normal[lex]];
		bins = Keys[Select[overlaps, # >= T &]];

		Switch[ Length[bins],
			0, lex["Insert",  (bins = Length[overlaps]) -> expr]; bins,
			1, First[bins],
			_, Sort[bins]]
		];
		
	<| "label" -> "BIN", "function" -> f, "clear" :> lex["KeyDropAll"] |>
	]		


(* 
General-purpose SDR encoder for dense vectors. 
*)
	
vectorencoder[config_Association] := Module[ {f, n, p, R = <||>},

	{n, p} = config["hyperparameters"];

	(* Encoding only. *)
	If[ config["component"] === output,
		Message[Circuit::encoder, vectorencoder]; Return[ <||>];];

	f[list_List] := Module[ {d, sparsity, vec, min, max, span, 
					scale, tolerance = 1.*^-10},

		d = Length[list];
		If[p <= 0 || d == 0, Return[{}]];
		
		sparsity = Lookup[config, "sparsity", N[1/Sqrt[d]]];
											(* Johnson-Lindenstrauss *)
		
		(* Lazy initialization of random sparse binary matrix. *)
		If[ MissingQ[R[d]], 
			R[d] = SparseArray[(QuotientRemainder[
				RandomSample[Range[n*d], Round[n*d*sparsity]]-1, d] + 1) -> 1,
				{n, d}]
			 ];

		vec = R[d] . list;
			
		(* Compute kWTA using rank p. *)
		(* Here we make no assumption about the bounds of the input data. *)
		{min, max} = MinMax[vec];
		span = max - min;
		scale = Max[Abs[min], Abs[max]];

		(* General-purpose dead switch. *)
		(* Reject if the array is zeros, or if the span is tiny relative 
			to the overall scale. *)
		If[scale == 0 || span <= tolerance * scale, Return[{}]];
		
		(* Standard kWTA *)
		Sort[Ordering[vec, -Min[p, Length[vec]]]]
		(* Note: This selects elements strictly in the original order,
		which may introduce a bias in certain datasets. *) 

		];

	<| "label" -> "VEC", "function" -> f, "clear" :> (R = <||>) |>
	]	


(* 
The textbook flyhash algorithm. 
*)
  
flyhash[config_Association] := 
	Module[{f, n, p, sparsity, R = <||>, restingpotential = <||>},
    
	{n, p} = config["hyperparameters"];

	sparsity = Lookup[config, "sparsity", 0.1];

	(* Encoding only. *)
	If[ config["component"] === output,
		Message[Circuit::encoder, flyhash]; Return[ <||>];];
    
   
    f[list_] := 
		Module[{d, c, centeredlist, vec, indices, min, max, span, 
					scale, tolerance = 1.*^-10},
     
		d = Length[list];
		If[p <= 0 || d == 0, Return[{}]];
     
		(* Input centering. Removes baseline firing magnitude. *)
		centeredlist = list - Mean[list];
     
		(* Fixed fan-in projection matrix. *)
		If[MissingQ[R[d]],
      
			(* The number of glomeruli each Kenyon cell samples from. *)
			c = Max[1, Round[d * sparsity]]; 
      
			(* Generate c distinct random column indices for each row. *)
			indices = Flatten[Table[{i, j}, {i, n}, 
				{j, RandomSample[Range[d], c]}], 1];
      
			(* Fixed biological resting potential, as static tie breaker. *)
			R[d] = SparseArray[indices -> 1, {n, d}];
			restingpotential[d] = RandomReal[{0, tolerance * 0.01}, n];
			];
     
		(* Pass signal, add the static resting potential to break ties. *)
		vec = R[d] . centeredlist + restingpotential[d];     
      
		(* General-purpose dead switch *)
		{min, max} = MinMax[vec];
		span = max - min;
		scale = Max[Abs[min], Abs[max]];
		If[scale == 0 || span <= tolerance * scale, Return[{}]];
     
		(* The APL neuron. Calculate standard kWTA. *)
		Sort[Ordering[vec, -Min[p, Length[vec]]]]
		];

	<| "label" -> "FLY", "function" -> f, "clear" :> (R = <||>) |>
	]  


(* 
At the beginning of each cycle, external input is pushed 
into the input's send slots. Input nodes have no "receive" slots.
A network may contain multiple input nodes.
Input data can be excitatory or inhibitory, or a mix.
The callback function serves as an optional encoder/preprocessing plugin.
*)
	
input[config_Association] := Module[ {plugin, c, sub},

	plugin = Lookup[config, "plugin", <| "function" -> Identity |>&];

	sub = Append[ config, "hyperparameters" -> First[config["send_parameters"]]];

	Join[ plugin[sub], <|"size" -> Small,  "checks" -> {"input", "oneout"} |> ]	
	]


(* 
At the end of each cycle, the output's input edges are read out.
Output nodes have no "send" slots.
A network may contain multiple output nodes.
Output data can be excitatory or inhibitory, or a mix.
The callback function serves as an optional decoder/postprocessing plugin.
*)

output[config_Association] := Module[ {plugin, c, sub},

	plugin = Lookup[config, "plugin", <| "function" -> Identity |>&];

	sub = Append[ config, "hyperparameters" -> First[config["receive_parameters"]]];

	Join[ plugin[sub], <|"size" -> Small,  "checks" -> {"output", "oneinp"} |> ]	
	]


(*
A delay node encapsulates five functions in one node:

- block coding
- signal delay
- proportional decimation by a factor D     (default: 1)
- rate limiting to max population R         (default: Infinity)
- temporal integration of C elements        (default: 0)

Multisets and inhibitory signals are handled transparently. 
Temporal integration resolves inhibition.
*)

delay[config_Association] := 
	Module[ {f, n, p, dims1, dims2, options, decimation, 
			ratelimit, capacity, Y = {}, label = ""},

	{n, p} = First[config["send_parameters"]]; 

	dims1 = First /@ config["receive_parameters"];
	dims2 = First /@ config["send_parameters"];

	options = Lookup[config, "options", <||>];

	(* Proportional stochastic subsampling for memory query. *)
	decimation = Lookup[options, "decimate", 1];
	(* Limit size of query pattern. Default: unlimited. *)			
	ratelimit  = Lookup[options, "rate_limit", Infinity];
	(* Temporal capacity, carry over from previous cycle. *)
	capacity = Lookup[options, "capacity", 0];				

	(* Visualization. *)
	If[decimation < 1, label = "decimate"];	
	If[ratelimit < Infinity, label = label <> "R"];	
	If[capacity > 0, label = label <> ".."];	

	f[blocks__List] := Module[ {X},
		
		X = MultisetBlockJoin[ {blocks}, dims1];
		
		(* X may be a mix of excitatory and inhibitory elements. 
			We let both fade at the same rate. *)
		If[decimation < 1,  (* This may result in an empty list. *)
			X = Sort[RandomSample[X, Floor[decimation Length[X]]]]]; 

		(* Rate limiting equally applies to positive and negative elements *)
		If[Length[X] > ratelimit, X = Sort[RandomSample[X, ratelimit]]]; 
		
		Y = RandomSample[Y, UpTo[capacity]]; 
		X = Multiset[X, Y]; (* Temporal integration. *)
		Y = X; (* Persist state. *)

		Sequence @@ MultisetBlockSplit[X, dims2]
		];

	<| "function" -> f, "checks" -> {"arginp", "argout", "totaldim"},
		"fill" -> 13, "label" -> label |>	
	]


(* 
A sample-and-hold latch with threshold and expiration.
Latches onto a signal if its population meets threshold T.
Holds and broadcasts the state for the specified number of additional cycles.
*)

latch[config_Association] := 
	Module[ {f, dims1, dims2, options, threshold, cycles, state, timer},

	dims1 = First /@ config["receive_parameters"];
	dims2 = First /@ config["send_parameters"];
	options = Lookup[config, "options", <||>];

	(* Hyperparameters *)
	(* Must have at least 1 element to latch by default. *)
	threshold = Lookup[options, "threshold", 1]; 
	
	(* Default window is Infinity. *)
	cycles = Lookup[options, "cycles", Infinity];
	
	(* Internal state and age tracker *)
	state = ConstantArray[{}, Length[dims2]];
	
	(* Start in an expired state. 
	If window is Infinity, Infinity + 1 simply evaluates to Infinity.
	*)
	timer = cycles + 1; 

	f[blocks__List] := Module[ {X},
		
		X = MultisetBlockJoin[ {blocks}, dims1];
		
		(* Event-driven latch: Update state if threshold is met. *)
		If[Length[X] >= threshold, 
			state = MultisetBlockSplit[X, dims2];
			timer = 0,
			
			(* Sub-threshold input: tick the timer only if within bounds. *)
			If[timer <= cycles, timer++];
			
			(* Check expiration. W=1 means the lifespan of the signal is 1. *)
			If[timer >= cycles, state = ConstantArray[{}, Length[dims2]]
			]
		];

		Sequence @@ state
		];

	<| "function" -> f, "checks" -> {"arginp", "argout", "totaldim"},
		"fill" -> 13, "label" -> "\[FilledRectangle]", "size" -> 17 |>	
	]


(* 
KWTA computed for multisets across multiple input slots.
Integrates time-bounding (cycles) and space-bounding (capacity).
Filters sparse signals below a minimum population threshold.

Note about the source of multisets: A single input pathway may already carry
a multiset ("+" modifier), or receive a multiset through pathway merging.
*)
	
kwta[config_Association] := 
	Module[ {f, dims1, dims2, options, k, cutoff, cycles, capacity, threshold, 
		window},

	dims1 = First /@ config["receive_parameters"];
	dims2 = First /@ config["send_parameters"];
	options = Lookup[config, "options", <||>];
	
	(* k is the population of the output channel. *)
	k = config["send_parameters"][[1, 2]]; 
	
	(* Temporal and space bounding parameters *)
	cycles    = Lookup[options, "cycles", 1];
	capacity  = Lookup[options, "capacity", Infinity];
	threshold = Lookup[options, "threshold", 0];
	
	(* Minimum number of occurrences. Acts as a high-pass filter. *)			
	cutoff = Lookup[options, "cutoff", 2];
		
	window = ConstantArray[{}, cycles];
	
	f[blocks__List] := Module[ {X, U, tally, rankedmax, winners = {}}, 

		X = MultisetBlockJoin[ {blocks}, dims1];

		(* Sub-threshold input: do not advance window, emit empty sets. *)
		If[Length[X] < threshold, 
			Return[Sequence @@ ConstantArray[{}, Length[dims2]]]
		];

		(* Event-driven window update: X is known to be >= threshold *)
		window = Rest[window];  AppendTo[window, X];
		
		(* Aggregate all positive elements from the current window *)
		U = Multiset[window]; 
		
		(* Capacity bounding: Unbiased subsampling if capacity is exceeded. *)

		(* Note: A biologically more plausible approach would apply either 
		   stochasitic exponential decay or linear  graded decay (multiset 
		   substraction). Modify as needed. See also: kwta component. *)
		  
		If[Length[U] > capacity,  U = Sort[RandomSample[U, capacity]]];
			
		(* KWTA consensus on the surviving elements *)
		tally = SortBy[Tally[U], Last]; 
		
		If[ Length[tally] >= k, 
			rankedmax = tally[[-k, 2]];
			If[rankedmax >= cutoff,
				winners = Sort[Select[tally, Last[#] >= rankedmax &][[All, 1]]]]
			];
		
		Sequence @@ MultisetBlockSplit[winners, dims2]
		];
		
	<| "function" -> f, "checks" -> {"arginp", "argout", "totaldim"}, 
		"label" -> "k", "fill" -> 13 |>
	]


(* Plug-in mechanism for auto-associative update rules. *)

replacement[y_,x_]   := y;
residual[y_, x_]     := Complement[x, y];
complement[y_, x_]   := Complement[y, x];
difference[args__]   := SymmetricDifference[args];
augmentation[args__] := Union[args];
coincidence[args__]  := Intersection[args];



(* 
Auto-associative memory component. 

Note: There is a wide range of possible learning, subsampling, retrieval 
and update rules for auto-associative memory. This prototype captures the 
geneneric cases. Modify as needed.
*)

auto[config_Association] := 
	Module[ {f, plugin, dims, options, p, M, label, size, min, max, 
		 ratelimit, decimation},
		
	(* Update rule *)			
	plugin = Lookup[config, "plugin", replacement];
			
	dims = First /@ config["receive_parameters"];
	options = Lookup[config, "options", <||>];
	p = Last[Plus @@ config["receive_parameters"]];

	{label, size} = 
		Switch[ plugin, 
			replacement,  {"\[FilledDownTriangle]", Large   },
			residual,     {"\[FilledUpTriangle]", Large   },
			complement,   {"\[EmptyDownTriangle]", Large   },
			difference,   {"\[EmptyUpTriangle]", Large   },
			augmentation, {"\[Union]", Medium  },
			coincidence,  {"\[Intersection]", Medium  },
			_,            {ToString[plugin],  Small   } (* User plug-in *)
		];

	(* Limit size of query pattern. Default: unlimited. *)			
	ratelimit  = Lookup[options, "rate_limit", Infinity];
	(* Proportional stochastic subsampling for memory query. *)
	decimation = Lookup[options, "decimate", 1];
	
	(* Learning thresholds. These apply to the total state, aggregated
	from all blocks. Modify this logic as needed. *)
	min = max = p; (* defaults *)
	If[ IntegerQ[options["learn"]], min = max = options["learn"] ];
	If[ MatchQ[options["learn"], {_Integer,_Integer}], {min, max} = options["learn"]];
	
	(* Memory with identical input and output parameters. *)
	M = Memory[#, #, Threshold -> Lookup[options, "threshold", Automatic]]& 
			[Plus @@ config["receive_parameters"]];
		
	f[blocks__List] := Module[ {A, X, Y, Xdec},

		(* Join partitions and apply inhibition. *)
		A = X = ResolveBlockJoinNormal[{blocks}, dims];
		
		(* Limit the rate of incoming positives. *)
		If[Length[X] > ratelimit, X = Sort[RandomSample[X, ratelimit]]];

		(* Note: Proportional decimation may result in an empty list. *)
		Xdec = If[decimation < 1, 
			Sort[RandomSample[X, Floor[decimation * Length[X]]]], X];
				

		(* Always learn if "learn"->True. Typically used for hyperassociations. *)
		If[options["learn"], M[A -> A]];

		(* Memory retrieval with decimated and rate-limited input state. *)
		Y = M[Xdec];

		(* Learn input A if retrieval fails *)
		If[Y === {} && Length[A] >= min && Length[A] <= max,
				If[options["learn"] =!= True, M[A -> A]]; Y = A];

		X = plugin[Y, X]; 

		Sequence @@ MultisetBlockSplit[X, dims] 
		]; 
		
	<| "function" -> f, "checks" -> {"arginp", "argout", "ident"}, 
		"label" :> label, "size" -> size,
	    "shape" -> "Square", "fill" -> 8, "clear" :> M[Clear] |>
	]


(* 
Vanilla hetero-associative node for supervised learning A -> B.
B is the first input argument.
A is given by the rest of the input arguments. Can be block-coded.
Always learns if B =!= {}.
*)

associator[config_Association] := 
	Module[ {f, options, Adims, M, decimation, oversampling},

	options = Lookup[config, "options", <||>];

	Adims = First /@ Rest[config["receive_parameters"]]; (* Dimensions of input blocks A *)

	(* Proportional stochastic subsampling for training.  *)
	decimation = Lookup[options, "decimate", 1];
	(* Proportional stochastic oversampling for training.  *)
	oversampling = Lookup[options, "oversampling", 1];
	
	(* Memory instance: *)
	M = Memory[Plus@@Rest[config["receive_parameters"]], First[config["send_parameters"]], 
				Threshold -> Lookup[options, "threshold", Automatic]];

	f[B_List, blocks__List] := Module[{X, Y},
		
		(* Apply and drop inhibitory elements. *)
		X = ResolveBlockJoinNormal[{blocks}, Adims];
		Y = ResolveNormal[B];
		
		If[Y === {}, Return[ M[X]]]; (* Test. *)
		
		(* Train. Optionally apply noise to avoid overfitting. *)
		If[decimation < 1, 
			X = Sort[RandomSample[X, Floor[decimation * Length[X]]]]];

		If[oversampling > 1, 
			X = Union[X, RandomSample[Range[Length[X], Round[(oversampling-1)
					 * Length[X]]]]]];

		M[X -> Y]; 
		{}	
		];   
		
		
	<| "function" -> f, "checks" -> { "dimfirst", "oneout"},
		"shape" -> "Square", "fill" -> 11, "size"-> (FontSize -> 18),
		"label"-> "\[FilledRightTriangle]\[FilledCircle]", "clear" :> M[Clear] |>
	]


(* 
Heteroencoder A -> B. A may be partitioned. Has no input for B.
*)

heteroencoder[config_Association] := 
	Module[ {f, options, dims, M},
	
	options = Lookup[config, "options", <||>];
	dims = First /@ config["receive_parameters"];
	
	M = Memory[ Plus @@ config["receive_parameters"], First[config["send_parameters"]], 
			Threshold -> Lookup[options, "threshold", Automatic]];
	
	f[blocks__List] := Module[{X, Y},
		X = ResolveBlockJoinNormal[{blocks}, dims];
		(* Retrieve. *)
		Y = M[X];
		
		(* Generate new SHR encoding if retrieval fails. *)
		If[Y === {}, 
			Y = Sort[RandomSample[Range[#1], #2]]& @@ First[config["send_parameters"]]];
		
		(* Always learn, broadening X as an attractor. *)
		M[X -> Y];
			
		Y
		]; 
			
	<| "function" -> f, "checks" -> {"arginp", "oneout"}, 
		"shape" -> "Square",  "fill" -> 11,  "size"-> (FontSize -> 18),
		"label" -> "\[FilledLeftTriangle]\[FilledRightTriangle]", "clear" :> M[Clear] |>
	]


(*
Generates a prediction based on the current input (slot #1) 
and context (slots #2,...).
Automatically learns the correct prediction in the following cycle.
To do so, the node remembers its context from the previous cycle.
*)

predictor[config_Association] := 
		Module[ {f, options, M, X = {}, prediction = {}, 
						itemconfig, contextconfig},

	options = Lookup[config, "options", <||>];
	itemconfig = First[config["receive_parameters"]];
	contextconfig = Rest[config["receive_parameters"]]; (* Context may be partitioned *)
	
	M = Memory[Plus @@ contextconfig, itemconfig,
		Threshold -> Lookup[options, "threshold", Automatic]]; 
	
	f[item_List, blocks__List] := Module[{Y},
	
		Y = ResolveNormal[item];
		
		(* State X and prediction from previous cycle *)
		(* Always learn. Also when the prediction was correct. *)
		M[X -> Y];
		
		X = ResolveBlockJoinNormal[ {blocks}, First /@ contextconfig];

		prediction = M[X]
		]; 


	<| "function" -> f, "checks" -> {"dimfirst", "oneout"}, 
		"shape" -> "Square", "fill" -> 11, "size"-> (FontSize -> 18),
		"label" -> "\[FilledRightTriangle]\[FilledRightTriangle]", "clear" :> M[Clear]
		|>
	]


(* 
Embedded circuit component.
*)
	
circuit[config_Association] := Module[ {f, subnet},
	
	subnet = Lookup[config, "plugin", Null];
	
	If[ ! MatchQ[subnet, _Symbol], Message[Circuit::circuit, subnet]; None];
	
	If[ {config["receive_parameters"], config["send_parameters"]} =!= {subnet[In], subnet[Out]},
		Message[Circuit::embedded, {subnet[In], subnet[Out]}]];
	
	(* Skip encoding and decoding *)
	f[blocks__] := Sequence @@ subnet[Function, {blocks}]; 
	

	<| "function" -> f, "checks" -> {"arginp", "argout"}, 
		"clear" :> subnet[Clear], 
		"shape" -> "Square", "size" -> Small, "label" -> ToString[subnet] |>
	]	


(* 
Random noise generator
*)
	
noise[config_Association] := Module[ {f},

	f[blocks___] := 
		Sort[RandomSample[Range[#1], #2]]& @@ First[config["send_parameters"]]; 
	
	<| "function" -> f, "checks" -> {"input", "oneout"}, "label" -> "~",
		"fill" -> 13, "size" -> 18 |>
	]	


(* Dataflow tags and their JSON names. *)
Circuit`TagMap = <|

"multiset"        -> "+", (* only multisets may contain negatives *)
"inhibit"         -> "-", (* if - then automatically + *) 
"permute"         -> "P", (* permuation, unique per pathway *)
"noise"           -> "~", (* random noise if empty, else clear elements *)
"rate_limit"      -> "R", (* stochastic rate limiting up to hyperparameter P *)
"threshold"       -> "T", (* clearing data below hyperparameter population P *)
"veto"            -> "X", (* clears all paths if any X path is non-empty *)
"mandatory"       -> "*", (* clears all paths if any * path is empty *)
"priority"        -> "!", (* clears all non-! paths if any ! path is non-empty *) 
"dependency"      -> "&", (* clears & paths if any non-& path is empty (AND) *)
"fallback"        -> "|", (* clears | paths if any non-| path is non-empty (NOR) *)
"barrier"         -> "=", (* clears = paths if any = path is empty *)
"kwta_excitatory" -> "K", (* top-k of positives *)
"kwta_absolute"   -> "k", (* top-k of all elements *)
"log"             -> "?", (* print log of path contents *)
"show_slot"       -> "#", (* render slot number *)
"show_dimension"  -> "$", (* render N *)
"show_population" -> "%"  (* render P *)

|>;

(* Note: temporal gating @... is handled separately. *)


Circuit[expr_] := Module[ 

		{ 
		circuit, self, 
	
		(* Compiler. *)
		compile, 
				
		(* Static compiled data. *)	
		nodes = <||>,
		pathways = <||>,
		
		preprocess  = {},        (* Encoding. One entry per input node. *)
		postprocess = {},        (* Decoding. One entry per output node. *) 
		
		inputslots = {},
		outputedges = {},
		
		permutations = <||>,

		(* Runtime functions. *)
		evaluate, patheval, componenteval,
									
		(* This circuit's clock. *)
		tick = 0,

		(* Slot state buffers. *)
		nextstate = <||>,
		currentstate = <||>,	
	
		nodeid = 0, edgeid = 0 
		},
		
	circuit = Switch[ expr,
	
		(* Raw circuit spec, e.g. imported from JSON or DFD. *)
		_Association /; KeyExistsQ[expr, "$schema"], expr,

		(* Convert from DFD (supported only in Mathematica). *)
		_List, FromDFD[expr],
		
		(* JSON file import. *)
		_String /; FileExistsQ[expr] && StringEndsQ[expr, ".json", IgnoreCase -> True],
			Import[expr, "Circuit"],

		(* JSON string. *)
		_String /; StringContainsQ[expr, "circuit-v1"],
			FromJSON[expr],

		_, Message[Circuit::circargs, expr]; Return[Null];
		];	
		
	
	self = Unique["c"];
	
	(* Expose this circuit's input and output configurations. Needed
	 by an enclosing circuit to check interface validity. *)
	self[In] = self[Out] = {};
				
	(* Compile a component. This triggers compilation of incoming pathways. *)
	compile[node_Association] := Module[
		{
		config, callback, compilepathway, slotparams, fillparams
		}, 
				
		++ nodeid;
		
		compilepathway[receive_] := Module[{e, tag},
			
			(* List of pathways denotes merging.  *)
			If[ ListQ[receive], Return[ compilepathway /@ receive]];

			++edgeid;

			tag[t_String] := MemberQ[ e["tags"], t]; 

			e = <|
				"to_node_id" -> nodeid, (* "from_node_id" added after all nodes are compiled *)
				"label" -> "", (* default. *)
				"tags" -> {} (* default. *)
				|>;
				
			Switch[ receive,
				_Integer, e["slot"] = receive,
				_Association, e = Join[e, receive],
				_, Message[Circuit::invedge,e]; <||>
				];
				
			e["hyperparameters"] = slotparams[e["slot"]];

			(* Helpful compiler: If "inhibit" then always "multiset" *)
			If[tag["inhibit"], 
				e["tags"] = Union[e["tags"], {"multiset"}]];				
			
			(* Register this pathway and initialize buffer. *)
			pathways[edgeid] = e;
			currentstate[e["slot"]] = {};
				 
			(* Initialize permutation for any pathway, even if it's not used. *)
			permutations[edgeid] = 
				RandomSample[Range[e["hyperparameters"][[1]]]];
					 
			edgeid	 
			];		
		
		(* Per-slot hyperparameter settings. *)
		slotparams[slot_Integer] := Module[{hyperparameters, default, np},
			hyperparameters = Lookup[circuit, "hyperparameters", <||>];
		
			default = Lookup[hyperparameters, "default", None];
			np = Lookup[hyperparameters, slot, default];
		
			If[ !MatchQ[np, {_Integer, _Integer}], 
					Message[Circuit::noparam, slot]; {100, 3}, np]
			(* Default to {100, 3} to silence downstream error messages. *)
			];

		fillparams[x_] := Switch[x, 
			_List, 
				Module[ {list, dims},
					list = fillparams /@ x; (* Recursion *)
					dims = list[[All,1]];
					If[! SameQ @@ dims, Message[Circuit::dimbundle, x]];
					(* Combine pathway dimensions. *)
					{dims[[1]], Min[list[[All, 2]]]}
					],
			_Integer, 
				slotparams[x],
			_Association, 
				slotparams[x["slot"]],
			_, Message[Circuit::routing, x]; Nothing 
			];
																			
		(* Base configuration for each node. Includes per-node user settings. *)
		config = Join[ node, 
			<|  
			"receive_paths" -> compilepathway /@ Lookup[node, "receive", {}],
		
			"id" -> nodeid, (* Used only for schematics visualization. *)
			
			(* Extract slot numbers *)
			"send_slots" -> Cases[Lookup[node, "send", {}], _Integer],

			"send_parameters" -> fillparams /@ Lookup[node, "send", {}], 
			"receive_parameters" -> fillparams /@ Lookup[node, "receive", {}]
			|>];
			
		
		(* Instantiate the component, re-append user options. *)
		config = Join[Lookup[node, "component"][config], config];
		
		(* Prepend default visualization settings. *)
		config = Join[<| "shape" -> "Circle", "label" -> "", "fill" -> 6, 
			"color" -> 0, "size" -> Medium  |>, config];

		(* Prepend default functional settings. *)
		config = Join[<| "checks" -> {}, "function" -> Null |>, config];

		(* Static error checking, based on component-supplied "checks". *)
		If[ ! Circuit`check[#][config["receive_parameters"], config["send_parameters"]], 
			Message[MessageName[Circuit, #], config]] & /@ config["checks"];

		(* Register input flow. *)
		If[Lookup[node, "component"] === input,  
			(* Register encoder. *)
			AppendTo[preprocess, config["function"]];
			AppendTo[inputslots, First[config["send_slots"]]];
			AppendTo[self[In], First[config["send_parameters"]]];

			config["label"] //= StringReplace["#" -> 
				ToString[Length[inputslots]]]
			];

		(* Register output flow. *)
		If[Lookup[node, "component"] === output, 
			(* Register decoder. *)
			AppendTo[postprocess, config["function"]];
			AppendTo[outputedges, First[config["receive_paths"]]];
			AppendTo[self[Out], First[config["receive_parameters"]]];

			config["label"] //= StringReplace["#" -> 
				ToString[Length[outputedges]]]
			];
				
		(* Register this component. *)
		nodes[nodeid] = config;
		];
	
	
	(* Compile the nodes. The nodes compile their inbound pathways. *)
	Scan[compile, Lookup[circuit, "dataflow", {}]]; 

	(* Link the edges. Needed for graph rendering. *)
	Module[ {slots, dupes, links = <||>, getlink},

		(* Duplicate sendslots? *)
		slots = Flatten[#["send_slots"] & /@ Values[nodes]];
		dupes = Keys[Select[Counts[{slots}], # > 1 &]];
		If[ Length[dupes] > 0, Message[Circuit::dupslots, dupes]];

		(* Gather link table. *)
		Scan[ Function[c, (links[#] = c["id"]) & /@ c["send_slots"]], 
			nodes];

		(* Add "from_node_id" value to each pathway. *)
		pathways = Prepend[#, "from_node_id" -> Lookup[links, #["slot"], 
			Message[Circuit::routing, #["slot"]]; 0]] & /@ pathways;		
		];

	(* 
	Component evaluation. Triggers evaluation of inbound pathways.
	*)
	componenteval[config_Association] := Module[ {x, result},

		(* Input and output nodes are not evaluated.*)		
		If[ MatchQ[config["component"], input | output], Return[]];
		
		(* Evaluate received pathways and latch inputs. *)
		x = patheval /@ config["receive_paths"];
			
		(* This component's callback function. *)
		result = config["function"][Sequence @@ x]; 

		(* Copy results to output slot. *)
		MapThread[(nextstate[#1] = #2) &, {config["send_slots"], {result}}]
		];
												
	(* 
	Pathway evaluation.
	During each cycle, this is triggered either by component evaluation
	(except output components), or explicitly when collecting outputs.*)

	patheval[id_Integer] := 
		Module[ {e, perm, x, tag, gating, n, p},
		
		tag[t_String] := MemberQ[ e["tags"], t]; 

		e = pathways[id];
		
		{n, p} = e["hyperparameters"];
		
		x = currentstate[e["slot"]];
		
		(* Runtime check. *)
		If[! VectorQ[x, IntegerQ] || MemberQ[x, 0], 
			Message[Circuit::integer, x]; Return[{}]];
				
		(* Process temporal gating (tags of the form @10101). *)
		gating = Lookup[e, "gating", {1}];
		If[ gating[[Mod[tick - 1, Length[gating]] + 1]] == 0, Return[{}]];
		
		(* 
		Inhibition transformer. Flips positives to negatives.
		This is the ONLY source of inhibition. 
		Normal pathways apply inhibitory elements and then drop them. 
		This enforces Dale's law. 
		*)
		If[tag["inhibit"], x = -Abs[x]];
		
		(*
		Carrier: forward resolved multiset.
		Boundary: untagged edges force resolution to a flat, excitatory set. 
		*)
		x = If[tag["multiset"], Multiset[x], ResolveNormal[x]];

		(* Permutation. *)
		If[tag["permute"],   
			x = Sort[Sign[x] * permutations[id][[Abs[x]]]] ];
	
		(* Rate limiting. *)
		If[tag["rate_limit"], x = Sort[RandomSample[x, UpTo[p]]]];

		(* Thresholding. *)
		If[tag["threshold"] && Length[x] < p, x = {}];

		(* Random noise if x = {}, else clear x *)
		If[tag["noise"], 
			If[x === {}, x = Sort[RandomSample[Range[n], p]], x = {}]];

		(* Print value to console. *)
		If[tag["log"], Print["Slot ", e["slot"], ": ", x]];
			
		x
		];
		

	(* 
	Pathway evaluation applied to a list (merging pathways). 
	*)
	patheval[ids : {__Integer}] := Module[ {x, paths, tags, merged},

		x = patheval /@ ids;
		
		paths = pathways /@ ids;
		
		(* List of Booleans with the same length as x. *)
		tags = Function[t, MemberQ[Lookup[#, "tags", {}], t] & /@ paths];		
		(* Logical gating. *)

		If[MemberQ[Pick[x, tags["veto"]], {__}], Return[{}]];

		If[MemberQ[Pick[x, tags["mandatory"]], {}], Return[{}]];

		If[MemberQ[Pick[x, tags["priority"]], {__}], 
			x = MapThread[If[#1, #2, {}] &, {tags["priority"], x}] ];

		If[MemberQ[Pick[x, Not /@ tags["dependency"]], {}], 
			x = MapThread[If[#1, {}, #2] &, {tags["dependency"], x}] ];
			
		If[MemberQ[Pick[x, Not /@ tags["fallback"]], {__}], 
			x = MapThread[If[#1, {}, #2] &, {tags["fallback"], x}] ];

		If[Or @@ tags["barrier"] && MemberQ[Pick[x, tags["barrier"]], {}],
             x = MapThread[If[#1, {}, #2]&, {tags["barrier"], x}]];

		(* Aggregate the survivors. *)
		merged = Multiset[x];
	
		(* Optional kWTA. *) 
		If[Or @@ tags["kwta_excitatory"] || Or @@ tags["kwta_absolute"],
			Module[{k, U, tally, rankedmax, excitQ, survivors},
			
				k = Min[#["hyperparameters"][[2]] & /@ paths ];
			
				(* "K" forces excitatory only. 
					"k" evaluates absolute saliency. *)
				excitQ = Or @@ tags["kwta_excitatory"];
			
				U = If[excitQ, Select[merged, # > 0 &], merged];
			
				tally = SortBy[Tally[U], Last];
			
				(* Force consensus: k elements must appear at least twice. *)
				merged = {};
				If[Length[tally] >= k, rankedmax = tally[[-k, 2]];
					If[ rankedmax >= 2, merged = Sort[Select[tally, 
						Last[#] >= rankedmax &][[All, 1]]]]
	   			]
	   		]
			];	
				
		merged
		];
		
	(* Raw tick-tock evaluation cycle. *)
	evaluate[x_List] := Module[ {},
		(* Advance this circuit's time. Used for multiplexing. *)
		tick ++;
		
		(* Optional clean-slate reset of nextstate, retaining all keys. 
		Safeguard for a scenario where a component fails to update nextstate. 
		nextstate = Map[{} &, currentstate];
		*)

		(*  Push external inputs to both slot buffers:
		      currentstate: for downstream pathway evaluation,
		      nextstate: because input components do not evaluate.
		 *)
		MapThread[(currentstate[#1] = nextstate[#1] = #2) &, {inputslots, x}];

		(* Evaluate nodes, reading from currentstate, updating nextstate. *)
		componenteval /@ nodes;

		(*  Snapshot state, preparing for output extraction and next cycle. *)
		currentstate = nextstate;
				
		(* Gather outputs, reading from currentstate. *)
		patheval /@ outputedges
		];

	(* 
	Raw evaluation with multiplexing.
	Skips preprocessing (encoding) and postprocessing (decoding).
	Exposed for use by embedded circuits.
	*)	
	self[Function, x_List] := Module[ {y = {}, multiplex},
	
		If[ Length[x] =!= Length[inputslots], 
			Message[Circuit::sequence, inputslots]; Return[Sequence[]]];
				
		(* Multiplexed evaluation of encoded data *)
		multiplex = Lookup[Lookup[circuit, "options", <||>], "multiplex", {1}];
		
		If[ ! MatchQ[ multiplex, {(0 | 1) ..}],
			Message[Circuit::multiplex, multiplex]; multiplex = {1}];
		
		Do[y = If[gate === 1, evaluate[x], 
			evaluate[{} & /@ x]], {gate, multiplex}];
			
		y (* Can be empty if all gates are zero. *)
		];			


	(* 
	The circuit specification generates this function. 
	Each call, even with empty inputs, triggers one execution cycle. 
	The function has a variable number of arguments which must match
	the number of input nodes.
	It returns a Sequence of expressions, each corresponding to an
	output node. The ordering of input and output arguments corresponds 
	to the order in which input and output nodes appear in the dataflow
	description. 	
	*)	
	self[blocks___] := Module[ {x, y},
	
		(* Wrap input sequence into a list. *)
		x = {blocks};
	
		(* Number of external input slots must match number of input nodes. *)
		If[ Length[x] =!= Length[inputslots], 
			Message[Circuit::sequence, inputslots]; Return[{}]];
				
		(* Preprocess (encode). *)
		x = MapThread[Construct, {preprocess, x}];
			
		(* Multiplexed evaluation of encoded data *)
		y = self[Function, x];		
		
		(* Postprocess (decode). *)
		y = MapThread[Construct, {postprocess, y}];	
			
		(* Strip list, return as sequence. *)
		Sequence @@ y
		];
		
	(* Visualization. *)
	self[Graph, opts___Rule] := Module[ 
		{ 
		graph, 
		layout = {"LayeredDigraphEmbedding", "Orientation" -> Left},
		coords = Automatic, radius = 0.4, colorscheme, 
		font = "Inter Variable", edgetag, display
		},
			
		(* Color palette lookup. *)
		colorscheme[c_] := Lookup[ Circuit`color, c, c];
		
		(* Convert tag names to single-character display labels. *)
		display = Reverse[Circuit`TagMap];
		display["inhibitory"] = "";
		display["multiset"]   = "";
		display["mandatory"]  = "\:ff0a"; (* A larger asterisk *)		
			
		edgetag[a_Association] := Module[ {str, rules},

			str = Lookup[a, "label", ""] <> 
				StringJoin[Lookup[display, #, ""]& /@ Lookup[a, "tags", {}]];
			
			rules = 				{
				display["show_slot"] -> ToString[a["slot"]],
				display["show_dimension"] -> ToString[a["hyperparameters"][[1]]],
				display["show_population"] -> ToString[a["hyperparameters"][[2]]]
				};
			
			StringReplace[str, rules]
			];
		
		(* Compile graph *)
		graph = DirectedEdge[#["from_node_id"], #["to_node_id"], 
				edgetag[#]]& /@ Values[pathways];
		
		(* Force path graphs to render on a single line. *)
		If[PathGraphQ[SimpleGraph[graph]],
			coords = (# -> {#, 0})& /@ Range[Length[nodes]]];
			
		Graph[ graph,
			PlotTheme -> "Classic",
			BaseStyle -> {FontFamily -> font, Opacity[1]},
			
			VertexSize -> radius,  
			
			VertexShapeFunction -> Normal[#["shape"] & /@ nodes],
			
			VertexStyle -> Normal[
				Directive[colorscheme[#["fill"]], 
				EdgeForm[Directive[colorscheme[1], AbsoluteThickness[0.15]]],
				Opacity[1]]& /@ nodes],

			VertexLabels -> Normal[ Placed[Style[#["label"], 
				colorscheme[#["color"]], 
				#["size"], Bold], Center]& /@ nodes],

			VertexCoordinates -> coords,

			EdgeStyle -> Normal[
				# -> Module[{tags = If[Length[#] == 3, #[[3]], ""]},

				Which[
 
				(* Multiset inhibitory (tag "-"): thick red *)
				StringMatchQ[tags, "*-*"],
				Directive[colorscheme[11], Opacity[1], AbsoluteThickness[3.5]], 
                       
				(* Multiset excitation (tag "+"): thick blue *)
				StringMatchQ[tags, "*+*"],
				Directive[colorscheme[8], Opacity[1], AbsoluteThickness[3.5]], 
            
				(* Default: dark gray and thin *)
				True,
				Directive[colorscheme[0], Opacity[1], AbsoluteThickness[0.5]]
				]] & /@ graph
				],


			EdgeLabels -> Normal[
				# -> If[Length[#] == 3,
				With[{cleanTag = StringReplace[#[[3]], 
					{"-" -> "" ,"+" -> "", "*" -> "\:ff0a"}]},
				If[cleanTag === "", 
				(* If the tag only contained hidden characters, hide it. *)
					None, 
					Placed[Framed[cleanTag, Background -> White, 
					FrameStyle -> None, 
					BaseStyle -> Directive[12, Bold, colorscheme[0]],
					RoundingRadius -> 30, FrameMargins -> 0], Center]]
				], None (* Hide labels for untagged edges. *)
				] & /@ graph],

			opts,
			GraphLayout -> layout
			]
		];	
		
	self[Clear] :=  Scan[#["clear"]&, nodes];
		
				
	self
	]


(* Plug-in mechanism for color palette. *)

Circuit`color = AssociationThread[Range[0,Length[#]-1],#]& [RGBColor /@ 
	{"#2E3440","#3B4252","#434C5E","#4C566A",
	"#D8DEE9","#E5E9F0","#ECEFF4","#8FBCBB",
	"#88C0D0","#81A1C1","#5E81AC","#BF616A",
	"#D08770","#EBCB8B","#A3BE8C","#B48EAD"}];


(* Plug-in mechanism for error messages. *)

Circuit::circargs  = "Invalid circuit specification `1`.";
Circuit::ident     = "`1`: Inputs must match outputs.";
Circuit::identdim  = "`1`: Input and output dimensions must be identical.";
Circuit::totaldim  = "`1`: Total input and output dimensions must match.";
Circuit::invedge   = "Invalid edge specification `1`.";
Circuit::dupslots  = "Duplicate output slots: `1`.";
Circuit::sequence  = "`1`: Function arguments do not match input nodes.";
Circuit::routing   = "Invalid routing specification `1`.";
Circuit::dimbundle = "`1`: Cannot bundle sets with different dimensions.";
Circuit::dimfirst  = "`1`: Output must match first input slot.";
Circuit::input     = "No input slots allowed in `1`.";
Circuit::oneinp    = "Expecting one input slot in `1`.";
Circuit::arginp    = "`1`: Missing input.";
Circuit::output    = "No output slots allowed in `1`.";
Circuit::oneout    = "`1`: Expecting one output slot.";
Circuit::argout    = "`1`: Missing output.";
Circuit::multinp   = "`1`: Expecting multiple input slots.";
Circuit::integer   = "Invalid data: `1`";
Circuit::circuit   = "`1`: Expecting embedded circuit.";
Circuit::embedded  = "`1`: Hyperparameters of embedded circuit do not match.";
Circuit::noparam   = "No hyperparameters specified for slot `1`.";
Circuit::category  = "Category encoder requires dimension `1` or greater.";
Circuit::encoder   = "`1` cannot be used as a decoder.";
Circuit::decoder   = "`1` cannot be used as an encoder.";
Circuit::regress   = "Regression: output should match `1`.";
Circuit::multiplex = "Malformed multiplex specification `1`.";


(* 
Plug-in mechanism for checking dataflow errors. 
#1 is the "receive" and #2 is the "send" specification. 
*)

Circuit`check = <||>;

Circuit`check["ident"]    = #1[[All,1]] === #2[[All,1]] &;
Circuit`check["identdim"] = Union[#1[[All,1]]] === Union[#2[[All,1]]] &;
Circuit`check["totaldim"] = Total[#1[[All,1]]] === Total[#2[[All,1]]] &;
Circuit`check["dimfirst"] = #1[[1]] === #2[[1]] &;
Circuit`check["input"]    = Length[#1] === 0 &;
Circuit`check["oneinp"]   = Length[#1] === 1 &;
Circuit`check["arginp"]   = Length[#1] > 0 &;
Circuit`check["output"]   = Length[#2] === 0 &;
Circuit`check["oneout"]   = Length[#2] === 1 &;
Circuit`check["argout"]   = Length[#2] > 0 &;


(*
Import and Export CircuitDFD dataflow description format:

  circ = Import["filename.m", "CircuitDFD"];
  Export["filename.m", circ, "CircuitDFD"];

Also supports ImportString and ExportString.
*)


(* 
Import from  DFD as used in GettingStarted and experiments. 
DFD is a native Mathematica expression and does not require parsing.
*)

FromDFD[dataflow_List] := Module[
    {rules, hyperparams = <||>, rootopts = <||>, customopts = <||>, 
     nodes, components, parsenode, parsepath, parsemerge},
    
    (* Include schema reference at the root *)
    AppendTo[rootopts, "$schema" -> "https://creatingintelligence.org/schemas/circuit-v1.json"];

    (* Extract all rules from the dataflow. *)
    rules = Select[dataflow, Head[#] === Rule &];
    
    (* Sort integers/blanks to hyperparameters, specific keys to root, and others to options. *)
    Scan[ Function[{rule}, Which[
        rule[[1]] === _, 
            AppendTo[hyperparams, "default" -> rule[[2]]],
 	
		IntegerQ[rule[[1]]], 
			AppendTo[hyperparams, rule[[1]] -> rule[[2]]],
        
		MemberQ[{"version", "metadata", "$schema"}, rule[[1]]],
            AppendTo[rootopts, rule[[1]] -> rule[[2]]],
        
        rule[[1]] === "multiplex" && StringQ[rule[[2]]],
            AppendTo[customopts, "multiplex" -> (If[# === "1", 1, 0] & /@ 
					Characters[rule[[2]]])],
        
        StringQ[rule[[1]]], 
            AppendTo[customopts, rule[[1]] -> rule[[2]]],

		True, 
            AppendTo[customopts, ToString[rule[[1]]] -> rule[[2]]]
         ]], rules
    ];
    
    (* Extract circuit components. *)
    nodes = Select[dataflow, Head[#] =!= Rule &];
    
    (* Helper to parse individual path strings into structured JSON objects *)
    parsepath[p_] := Module[
        {s = ToString[p], match, slot, tags, tagmap, 
            found, result = <||>, tagPattern, parts},
        
        match = StringCases[s, StartOfString ~~ n:DigitCharacter.. ~~ Whitespace... ~~ t:___ ~~ EndOfString :> {ToExpression[n], t}];
        
        If[match === {}, 
            tagPattern = (Alternatives @@ Join[Values[Circuit`TagMap], {" "}] | ("@" ~~ DigitCharacter..))..;
            If[StringMatchQ[s, tagPattern], match = {{1, s}}, Return[s]]
			];
        
        {slot, tags} = match[[1]];
        If[tags === "", Return[slot]];
        
        result["slot"] = slot;
        
        If[StringContainsQ[tags, " "],
            parts = StringSplit[tags, " ", 2];
            result["label"] = parts[[1]];
            tags = parts[[2]]];
        
        With[{g = StringCases[tags, "@" ~~ val:(DigitCharacter..) :> val]},
            If[Length[g] > 0,
                result["gating"] = If[# === "1", 1, 0] & /@ Characters[g[[1]]];
                tags = StringReplace[tags, "@" ~~ g[[1]] -> ""]; 
				]
			];
        
        tagmap = Association[Reverse /@ Normal[Circuit`TagMap]];
		found = Values[KeyTake[tagmap, Characters[tags]]];
        If[Length[found] > 0, result["tags"] = found];
        
        result
		];

    parsemerge[l_List] := parsepath /@ l;
    parsemerge[p_] := parsepath[p];

	parsenode[compExpr_[send___][receive___]] := Module
		[
        {comp, compName, argslist, label = Null, plugin = Null, opts = <||>},
        
        comp = Head[compExpr]; 
        compName = ToString[comp];
        argslist = List @@ compExpr; 
        
        Do[ Which
			[
			Head[arg] === Rule, AppendTo[opts, arg],
			StringQ[arg] && label === Null && plugin === Null, label = arg,
			True, plugin = arg], {arg, argslist}
			];
        
        DeleteCases[ 
			<|
            "component" -> comp, 
            "label" -> label,
            "plugin" -> plugin,
            "options" -> opts,
            "send" -> Map[parsemerge, Flatten[{send}, 1]],
            "receive" -> Map[parsemerge, {receive}]
            |>, 
            Null | {} | <||> 
        ]
    ];
        
    components = parsenode /@ nodes;
    If[Length[customopts] > 0, AppendTo[rootopts, "options" -> customopts]];

    Join[rootopts, <|"hyperparameters" -> hyperparams, "dataflow" -> components|>]
	]


ToDFD[expr_Association] := Module[

    {hyperparams, hprules, topoptsrules, dataflow, buildpath, 
     buildmerge, parsenode, nodeExprs, rawOptions},

    rawOptions = Join[
        KeyDrop[expr, {"hyperparameters", "dataflow", "options", "$schema"}],
        Lookup[expr, "options", <||>]
		];

    topoptsrules = Normal @ KeyValueMap[
        Function[{k, v},
            Which[
                k === "multiplex" && ListQ[v], "multiplex" -> StringJoin[ToString /@ v],
                True, k -> v
            ]], rawOptions
		];

	hyperparams = Lookup[expr, "hyperparameters", <||>];

	hprules = KeyValueMap[
        Function[{k, v},
            Which[
                k === "default", _ -> v,
                StringQ[k] && StringMatchQ[k, NumberString], ToExpression[k] -> v, 
                True, k -> v 
            ]],
        hyperparams
		];
    
    buildpath[p_] := Module[{slot, tags = "", tagstr = "", gatingStr = "", userlabel = ""},
        If[IntegerQ[p] || StringQ[p], Return[p]];
        slot = p["slot"];
        If[KeyExistsQ[p, "tags"], tagstr = StringJoin[Lookup[Circuit`TagMap, p["tags"], ""]]];
        If[KeyExistsQ[p, "gating"], gatingStr = "@" <> StringJoin[ToString /@ p["gating"]]];
        If[KeyExistsQ[p, "label"], userlabel = p["label"] <> " "];
        
        tags = userlabel <> tagstr <> gatingStr;
        If[tags === "", slot, slot * tags]
		];

    buildmerge[l_List] := buildpath /@ l;
    buildmerge[p_] := buildpath[p];

	parsenode[node_Association] := Module[
        
        {comp, compName, label, plugin, opts, send, receive, compExpr},
        
        comp = node["component"]; 
        compName = ToString[comp];
        label = Lookup[node, "label", Null];
        plugin = Lookup[node, "plugin", Null];
        opts = Normal[Lookup[node, "options", <||>]];
        
        compExpr = comp @@ DeleteCases[Join[If[label =!= Null, {label}, {}], If[plugin =!= Null, {plugin}, {}], opts], Null];
        
        send = Sequence @@ Map[buildmerge, Lookup[node, "send", {}]];
                              
        receive = Sequence @@ Map[buildmerge, Lookup[node, "receive", {}]];
        
        compExpr[send][receive]
		];
		
    dataflow = Lookup[expr, "dataflow", {}];
    nodeExprs = parsenode /@ dataflow;

    Join[nodeExprs, hprules, topoptsrules]
	]



ImportExport`RegisterFormat["CircuitDFD", "DefaultExtension" -> "m"];

ExportCircuitDFDHook[channel_, expr_Association, opts___] := Module[{str},
    (* Export to string to preserve indentation, strip the comment, and write as raw text *)
    str = ExportString[ToDFD[expr], "Package"];
             
	str = StringDelete[str, RegularExpression["\\(\\* Created.*?\\*\\)\\n"]];          
    
    Export[channel, str, "Text"]
	]

ImportCircuitDFDHook[channel_, opts___] := Module[{data, isString},
    (* Heuristic: if it's a string but doesn't look like a file path, treat as raw text *)
    isString = StringQ[channel] && !StringMatchQ[channel, "*.*"] && !FileExistsQ[channel];
    
    data = If[isString, 
        ImportString[channel, "Package"], 
        Import[channel, "Package"]
    ];
    
    FromDFD[data]
	]

ImportExport`RegisterExport["CircuitDFD", ExportCircuitDFDHook];
ImportExport`RegisterImport["CircuitDFD", ImportCircuitDFDHook];



(*
Import and Export JSON format:
  circ = Import["filename.json", "Circuit"];
  Export["filename.json", circ, "Circuit"];

Also supports ImportString and ExportString.
*)


ToJSON[expr_Association] := Module[

    {decodeBytes, cleanString, formatrootelement, rootStrList, dfStrList, dfStr, prepareNode},
    
    decodeBytes[s_String] := 
        If[Max[ToCharacterCode[s]] <= 255, 
            FromCharacterCode[ToCharacterCode[s], "UTF8"], s ];
    
    cleanString[s_String] := StringReplace[s, {"\":" -> "\": ", "," -> ", ", "\\/" -> "/"}];
    
    formatrootelement[k_String] := 
        "\"" <> k <> "\": " <> cleanString @ decodeBytes @ 
            ExportString[
                If[k === "hyperparameters", KeyMap[ToString, expr[k]], expr[k]], 
                "RawJSON", "Compact" -> True
            ];
    
    rootStrList = formatrootelement /@ Keys[KeyDrop[expr, {"dataflow"}]];
    
	prepareNode[node_Association] := Module[{n = node},
        If[KeyExistsQ[n, "component"], 
            n["component"] = ToString[n["component"]]];
            
        If[KeyExistsQ[n, "plugin"], 
            n["plugin"] = ToString[n["plugin"], InputForm]];
            
        n
		];  
		      
    dfStrList = (cleanString @ decodeBytes @ 
		ExportString[prepareNode[#], "RawJSON", "Compact" -> True] &) /@ 
			expr["dataflow"];
    
    dfStr = "\"dataflow\": [\n    " <> StringRiffle[dfStrList, ",\n\n    "] 
			<> "\n  ]";
    
    "{\n  " <> StringRiffle[Append[rootStrList, dfStr], ",\n\n  "] <> "\n}"
	]


FromJSON[jsonString_String] := Module[
    {expr},

	expr = ImportString[jsonString, "RawJSON"];
    
	If[KeyExistsQ[expr, "hyperparameters"],
        expr["hyperparameters"] = KeyMap[
            If[StringMatchQ[#, NumberString], ToExpression[#], #] &, 
            expr["hyperparameters"]] ];
    
	If[KeyExistsQ[expr, "dataflow"],
        expr["dataflow"] = Map[ Function[node,
			Module[{n = node},
			
				If[KeyExistsQ[n, "component"] && StringQ[n["component"]],
					n["component"] = ToExpression[n["component"]]];
					
				If[KeyExistsQ[n, "plugin"],
					n["plugin"] = ToExpression[n["plugin"]]];
				n
                ]
            ],
            expr["dataflow"]]
		];
		    
    expr
	]


(* 
JSON format hooks ("Circuit") 
*)

ImportExport`RegisterFormat["Circuit", "DefaultExtension" -> "json"];


ExportCircuitHook[channel_, expr_Association, opts___] := 
    Export[channel, ToJSON[expr], "Text", CharacterEncoding -> "UTF8"]


ImportCircuitHook[channel_, opts___] := Module[
    {isString, expr},
    
    isString = StringQ[channel] && StringMatchQ[StringTrim[channel], "{*" | "[*"];
    
    expr = If[isString,
        ImportString[channel, "RawJSON"],
        Import[channel, "RawJSON"]];
    
    If[KeyExistsQ[expr, "hyperparameters"],
        expr["hyperparameters"] = KeyMap[
            If[StringMatchQ[#, NumberString], ToExpression[#], #] &, 
            expr["hyperparameters"]
        ]];
    
    If[KeyExistsQ[expr, "dataflow"],
        expr["dataflow"] = Map[
            Function[node,
                Module[{n = node},
                
                    If[KeyExistsQ[n, "component"] && StringQ[n["component"]],
                        n["component"] = ToExpression[n["component"]]];
                        
                    If[KeyExistsQ[n, "plugin"],
                        n["plugin"] = ToExpression[n["plugin"]]];
                        
                    If[n["component"] === input && KeyExistsQ[n, "receive"],
                        n["receive"] = ToExpression /@ n["receive"]];
                        
                    If[n["component"] === output && KeyExistsQ[n, "send"],
                        n["send"] = ToExpression /@ n["send"]];
                        
                    n
                ]
            ],
            expr["dataflow"]]
		];
    
    expr
	]

ImportExport`RegisterExport["Circuit", ExportCircuitHook];
ImportExport`RegisterImport["Circuit", ImportCircuitHook];


(* 
A formatting-invariant hash of a JSON string, used for filename generation.
*)

JSONHash[data_String] := Module[{sorted, jsonString, hexHash},
    sorted = Replace[data, a_Association :> KeySort[a], {0, Infinity}];
    
    jsonString = ExportString[sorted, "JSON", "Compact" -> True, 
        CharacterEncoding -> "UTF-8"];
    
    jsonString = StringReplace[jsonString, "\\/" -> "/"];
    jsonString = StringTrim[jsonString];
    
    hexHash = Hash[jsonString, "SHA256", "HexString"];
    
    StringTake[hexHash, 12]
 ]


(* -------------------------------------------------------------------------- *)
