(* ::Package:: *)

(************************************************************************)\012(* This file was generated automatically by the Mathematica front end.  *)\012(* It contains Initialization cells from a Notebook file, which         *)\012(* typically will have the same name as this file except ending in      *)\012(* ".nb" instead of ".m".                                               *)\012(*                                                                      *)\012(* This file is intended to be loaded into the Mathematica kernel using *)\012(* the package loading commands Get or Needs.  Doing so is equivalent   *)\012(* to using the Evaluate Initialization Cells menu command in the front *)\012(* end.                                                                 *)\012(*                                                                      *)\012(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)\012(* automatically each time the parent Notebook file is saved in the     *)\012(* Mathematica front end.  Any changes you make to this file will be    *)\012(* overwritten.                                                         *)\012(************************************************************************)\012\012

(*
Copyright (c) 2026 Peter Overmann
 
SPDX-License-Identifier: MIT
 
This file is part of the "Creating Intelligence" project. It is licensed 
under the MIT License. You may obtain a copy of the License in the LICENSE 
file in the root directory of this repository.
 
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR 
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, 
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
*)


(*
This native Mathematica implementation of topological associative memory
is optimized for speed. 
See "Memory Reference.nb" for a plain reference implementation.
*)



Memory[config_Association] :=

	Module[ {mem = <||>, NA, PA, NB, PB, T = 1, capacity, zero,
		store, retrieve, clear, memorycount, accumulate},
			
		{NA, PA} = config["A_parameters"];
		{NB, PB} = config["B_parameters"];
		
		If[ ! MatchQ[{NA, PA, NB, PB}, {__Integer}], 
					Message[Memory::params, config]];	

		(* Memory capacity, needed for default threshold calculation. *)
		capacity = If[NA == NB && PA == PB, 
				Log[2.0] NA (NA - 1) (NA - 2) / (PA (PA - 1) (PA - 2)),
				Log[2.0] NA (NA - 1) NB / (PA (PA - 1) PB)];
			
		(* Default pattern matching threshold. *)
		While[T < PA && capacity^2 * Binomial[PA, T] * Binomial[NA-PA, PA-T] / 
				Binomial[NA, PA] >= 1, T++];

		(* User-defined (scaled) threshold . *)
		If[KeyExistsQ[config, "threshold"] && NumberQ[config["threshold"]],
			T = Round[config["threshold"] * PA]];
			
		If[T < 2, T = 2];

		zero = Developer`ToPackedArray[ConstantArray[0, NB]];

		(* Store auto-association A -> A in memory. *)
		store[A_List] := store[A, A];
		
		(* Store hetero-association A -> B in memory. *)
		store[A_List, B_List] := Module[{keys, existing},
			If[Length[A] < 2, Return[]];
			
			(* Step 1: Expansion coding. *)
			keys = Subsets[A, {2}];
			
			(* Step 2: Bulk memory retrieval. *)
			existing = Lookup[mem, keys, zero];
			
			(* Step 3: Vectorized memory update. *)
			existing[[All, B]] = 1;
			
			(* Step 4: Bulk memory commit. *)
			AssociateTo[mem, AssociationThread[keys, existing]];
		];
		
		(* Helper function. *)
		accumulate = Compile[{{P, _Integer}, {valsY, _Integer, 1}},
			Module[{w = Table[0, {P}], k = 1},
				Do[
					w[[i]] += valsY[[k]];
					w[[j]] += valsY[[k]];
					k++,
				{i, 1, P - 1}, {j, i + 1, P} ];
				w], RuntimeOptions -> "Speed"
			];

		(* Memory retrieval. *)
		retrieve[A_List] := 
			Module[{X = A, P, Y, R, vals, valsY, t, w, ws, h, cutoff},
			
			While[True,
			
				P = Length[X];
				If[P < T, Return[{}]];

				(* Bulk native lookup returning a 2D packed C-array *)
				vals = Lookup[mem, Subsets[X, {2}], zero];

				(* Vectorized column accumulation *)
				R = Total[vals];

				t = Max[1, R[[First @ Ordering[R, -PB]]]];
				If[t < T (T - 1) / 2, Return[{}]];

				Y = Pick[Range[NB], UnitStep[R - t], 1];

				(* Slice array to columns Y and row-reduce to scalar pair weights *)
				valsY = Total[vals[[All, Y]], {2}];

				(* 1D compiled distribution to element weights *)
				w = accumulate[P, valsY];

				ws = Sort[w];
				h = P;
				While[(cutoff = ws[[-h]]) < Length[Y] * (h - 1), --h];

				If[h < T, Return[{}]];

				X = Pick[X, UnitStep[w - cutoff], 1];

				If[h === T && h < Length[X], Return[{}]];
				If[Length[X] == P, Return[Y]];
				]
			];	
  		
		clear := (mem = <||>;);
		memorycount := Total[Values[mem], 2];
				
		<|
			"A_parameters" -> {NA, PA},
			"B_parameters" -> {NB, PB},
			"T" -> T, (* Absolute pattern matching threshold. *)
			"store" -> store,
			"retrieve" -> retrieve,
			"clear" :> clear,
			"memorycount" :> memorycount,
			"backend" -> "Mathematica"
		|>
		]


Memory::params  = "Invalid hyperparameters: `1`";



