(* ::Package:: *)

(************************************************************************)\012(* This file was generated automatically by the Mathematica front end.  *)\012(* It contains Initialization cells from a Notebook file, which         *)\012(* typically will have the same name as this file except ending in      *)\012(* ".nb" instead of ".m".                                               *)\012(*                                                                      *)\012(* This file is intended to be loaded into the Mathematica kernel using *)\012(* the package loading commands Get or Needs.  Doing so is equivalent   *)\012(* to using the Evaluate Initialization Cells menu command in the front *)\012(* end.                                                                 *)\012(*                                                                      *)\012(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)\012(* automatically each time the parent Notebook file is saved in the     *)\012(* Mathematica front end.  Any changes you make to this file will be    *)\012(* overwritten.                                                         *)\012(************************************************************************)\012\012

(*
Copyright (c) 2026 Peter Overmann
 
SPDX-License-Identifier: MIT
 
This file is part of the "Creating Intelligence" project. It is licensed 
under the MIT License. You may obtain a copy of the License in the LICENSE 
file in the root directory of this repository.
 
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR 
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, 
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
*)


Options[Memory] = {Threshold -> Automatic};


Memory[{NA_Integer, PA_Integer}, {NB_Integer, PB_Integer}, OptionsPattern[]] := 

	Module[ {f, mem = <||>, T = 1, cap, zero},
	
		f = Unique["mem"];
		
		(* Memory capacity. *)
		cap = If[NA == NB, 
				Log[2.0] NA (NA - 1) (NA - 2) / (PA (PA - 1) (PA - 2)),
				Log[2.0] NA (NA - 1) NB / (PA (PA - 1) PB)];
			
		(* Pattern matching threshold. *)
		While[T < PA && cap^2 * Binomial[PA, T] * Binomial[NA - PA, PA - T] / 
				Binomial[NA, PA]  >= 1, T++];

		If[IntegerQ[ OptionValue[Threshold]], T = OptionValue[Threshold]];
		If[T < 2, T = 2];

		zero = Developer`ToPackedArray[ConstantArray[0, NB]];

		(* Store A -> B in memory. *)
		f[A_List -> B_List] := Module[{v, sub2},
			(* Step 1: Expansion coding. *)
			sub2 = Subsets[A, {2}];
		
			(* Step 2: Memory update. *)
			v = zero; v[[B]] = 1; 
			(mem[#] = BitOr[Lookup[mem, Key[#], zero], v])& /@ sub2; 
			];

		(* Memory retrieval. *)
		f[A_List] := Module[ {X, P, Y, R, Ri, sub2, v, t, w, ws, h, cutoff},
			(* Step 1: Initialize. *)
			X = A; 
			
			While[ True,
				(* Step 2: Threshold check.  *)
				If[ (P = Length[X]) < T, Return[{}]]; 
			
				(* Step 3: Expansion coding. *)
				sub2 = Subsets[Range[P], {2}];
			
				(* Step 4: Aggregate. *)
				Ri = ConstantArray[0, {P, NB}];
				(v = Lookup[mem, Key[{X[[#1]], X[[#2]]}], zero]; 
						Ri[[#1]] += v; Ri[[#2]] += v) & @@@ sub2;
				R = (Plus @@ Ri) / 2; 
			
				(* Step 5: Select (kWTA with threshold T(T-1)/2) *)
				(* The first element of a negative Ordering is the index 
					of the k-th largest value. Use this for the threshold check. *)
				t = Max[1, R[[First @ Ordering[R, -PB]]]];
				
				(* Step 6: Threshold check. *)
				If[ t < T (T - 1) / 2, Return[{}]]; 
				Y = Sort[Pick[Range[NB], UnitStep[R - t], 1]];
			
				(* Step 7: Per-element weights. *)
				w = Total /@ Ri[[All, Y]];
				
				(* Step 8: Convergence test.  *)
				ws = Sort[w]; 
				h = P;
				While[ (cutoff = ws[[-h]]) < Length[Y] * (h - 1), --h];

				If[ h < T, Return[{}]]; 		
				
				(* Step 9: Refine. *)
				X = Pick[X, # >= cutoff & /@ w];
				
				(* Handle edge case. *)
				If[h === T &&  h < Length[X], X = {}; Return[{}]];
				
				(* Finished if X has converged. *)
				If[Length[X] == P, Return[Y]]; 

				(* Step 10: Iterate.  *)
				]
			];

		f["memorycount"] := Total[Values[mem], 2];		
		
		f[Clear] := (mem = <||>; ClearAll[Evaluate[f]]); 
		f
		]



