[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "creating-intelligence"
version = "0.1.0a4"
dynamic = ["dependencies"]
description = "A computational foundation for AGI, based on hyperdimensional sparse data and framed in set theory."
readme = "README.md"
requires-python = ">=3.8"
authors = [{ name = "Peter Overmann", email = "mail@creatingintelligence.org" }]
license = "MIT"
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: C",
    "Operating System :: OS Independent",
]

keywords = [
    "artificial intelligence",
    "computational theory of mind",
    "hyperdimensional computing",
    "sparse distributed representations",
    "topological associative memory",
    "subset matching algorithm",
    "spiking neural networks",
    "neuromorphic computing",
    "theoretical neuroscience"
]

[tool.setuptools.dynamic]
dependencies = {file = ["requirements.txt"]}

[tool.setuptools.packages.find]
where = ["."]
include = ["creating_intelligence*"]

[project.urls]
Homepage = "https://creatingintelligence.org"
Documentation = "https://creatingintelligence.org/docs"
Repository = "https://github.com/peterovermann/creatingintelligence"