

# make file for commandline tool and test program 

all:
	cc -O3 -ffast-math commandline.c memory.c -o /usr/local/bin/memory
	cc -O3 -ffast-math testing.c     memory.c -o /usr/local/bin/memorytest
	